classdef ErrorRegistry
    % ErrorRegistry - Global error code taxonomy and registry for MECH0020
    %
    % Purpose:
    %   Single source of truth for all error codes across the repository
    %   Provides lookup for error metadata (severity, category, remediation)
    %
    % Error Code Format: PREFIX-CATEGORY-NNNN
    %   PREFIX: Module/subsystem identifier
    %   CATEGORY: Error category or severity indicator
    %   NNNN: Unique number within category
    %
    % Usage:
    %   info = ErrorRegistry.lookup('SYS-BOOT-0001');
    %   all_codes = ErrorRegistry.get_all_codes();
    %   ErrorRegistry.print_registry();  % Print all error codes
    %
    % Categories:
    %   SYS-BOOT-xxxx:  System bootstrap (startup, path setup, initialization)
    %   CFG-VAL-xxxx:   Configuration validation
    %   UI-LAY-xxxx:    UI layout issues
    %   UI-CB-xxxx:     UI callback errors
    %   RUN-EXEC-xxxx:  Runner/dispatcher execution
    %   SOL-FD-xxxx:    Finite Difference solver
    %   SOL-SP-xxxx:    Spectral solver
    %   SOL-FV-xxxx:    Finite Volume solver
    %   SOL-PL-xxxx:    Placeholder/unimplemented method entries
    %   IO-FS-xxxx:     Filesystem I/O
    %   MON-SUS-xxxx:   Sustainability monitors
    %   TST-xxxx:       Testing framework
    %   GEN-xxxx:       Generic/uncategorized errors

    methods (Static)
        function info = lookup(error_code)
            % Look up error code metadata
            %
            % Returns struct with:
            %   code:        Error code
            %   severity:    'CRITICAL' | 'ERROR' | 'WARN' | 'INFO'
            %   category:    Human-readable category
            %   description: What this error means
            %   remediation: How to fix it
            %   causes:      Common causes (cell array)

            registry = ErrorRegistry.build_registry();

            field_name = strrep(error_code, '-', '_');
            if isfield(registry, field_name)
                info = registry.(field_name);
            else
                % Unknown error code - return generic
                info = struct(...
                    'code', error_code, ...
                    'severity', 'ERROR', ...
                    'category', 'Unknown', ...
                    'description', 'Unknown error code', ...
                    'remediation', 'Check error code spelling or update ErrorRegistry', ...
                    'causes', {{'Error code not registered'}});
            end
        end

        function codes = get_all_codes()
            % Get list of all registered error codes
            registry = ErrorRegistry.build_registry();
            codes = fieldnames(registry);
        end

        function print_registry()
            % Print all error codes and their descriptions
            registry = ErrorRegistry.build_registry();
            codes = fieldnames(registry);

            fprintf('\n');
            fprintf('═══════════════════════════════════════════════════════════════\n');
            fprintf('  MECH0020 ERROR CODE REGISTRY\n');
            fprintf('═══════════════════════════════════════════════════════════════\n\n');

            fprintf('Total error codes: %d\n\n', length(codes));

            % Group by prefix using unique extraction
            prefix_list = cell(length(codes), 1);
            for i = 1:length(codes)
                parts = strsplit(codes{i}, '-');
                prefix_list{i} = parts{1};
            end
            prefixes = sort(unique(prefix_list));

            for p = 1:length(prefixes)
                prefix = prefixes{p};
                fprintf('─────────────────────────────────────────────────────────────\n');
                fprintf('  %s - %s\n', prefix, ErrorRegistry.get_prefix_description(prefix));
                fprintf('─────────────────────────────────────────────────────────────\n\n');

                for i = 1:length(codes)
                    if startsWith(codes{i}, prefix)
                        info = registry.(codes{i});
                        fprintf('[%s] %s\n', info.severity, info.code);
                        fprintf('  %s\n', info.description);
                        fprintf('  Fix: %s\n\n', info.remediation);
                    end
                end
            end
        end

        function desc = get_prefix_description(prefix)
            % Get description for  error code prefix
            switch prefix
                case 'SYS'
                    desc = 'System Bootstrap & Initialization';
                case 'CFG'
                    desc = 'Configuration & Validation';
                case 'UI'
                    desc = 'User Interface';
                case 'RUN'
                    desc = 'Runner & Dispatcher';
                case 'SOL'
                    desc = 'Solver Modules';
                case 'IO'
                    desc = 'File I/O & Persistence';
                case 'MON'
                    desc = 'Monitoring & Sustainability';
                case 'TST'
                    desc = 'Testing Framework';
                case 'GEN'
                    desc = 'Generic Errors';
                otherwise
                    desc = 'Other';
            end
        end

        function registry = build_registry()
            % Build the complete error registry
            % Each entry: code, severity, category, description, remediation, causes

            registry = struct();

            % ===== SYS-BOOT: System Bootstrap =====
            registry.SYS_BOOT_0001 = struct(...
                'code', 'SYS-BOOT-0001', ...
                'severity', 'CRITICAL', ...
                'category', 'Path Setup', ...
                'description', 'Failed to locate repository root directory', ...
                'remediation', 'Ensure .git folder exists or run from within repository', ...
                'causes', {{'Not running from repo directory', 'Repo structure corrupted'}});

            registry.SYS_BOOT_0002 = struct(...
                'code', 'SYS-BOOT-0002', ...
                'severity', 'CRITICAL', ...
                'category', 'Path Setup', ...
                'description', 'Required directory missing from repository', ...
                'remediation', 'Run PathSetup.attach_and_verify() and check repository integrity', ...
                'causes', {{'Fresh clone without Data/Output/', 'Repo corruption'}});

            registry.SYS_BOOT_0003 = struct(...
                'code', 'SYS-BOOT-0003', ...
                'severity', 'ERROR', ...
                'category', 'Dependency', ...
                'description', 'Required MATLAB function or class not found', ...
                'remediation', 'Ensure all Scripts subdirectories are on path', ...
                'causes', {{'addpath not called', 'Missing .m file', 'Typo in function name'}});

            % ===== CFG-VAL: Configuration Validation =====
            registry.CFG_VAL_0001 = struct(...
                'code', 'CFG-VAL-0001', ...
                'severity', 'ERROR', ...
                'category', 'Parameter Validation', ...
                'description', 'Invalid grid resolution (Nx or Ny)', ...
                'remediation', 'Set Nx and Ny to positive integers >= 16', ...
                'causes', {{'Nx/Ny too small', 'Nx/Ny not integer', 'Nx/Ny negative or zero'}});

            registry.CFG_VAL_0002 = struct(...
                'code', 'CFG-VAL-0002', ...
                'severity', 'ERROR', ...
                'category', 'Parameter Validation', ...
                'description', 'Invalid time step (dt) or final time (Tfinal)', ...
                'remediation', 'Set dt > 0 and Tfinal > dt; check CFL condition', ...
                'causes', {{'dt too large (CFL violation)', 'dt or Tfinal non-positive', 'Tfinal < dt'}});

            registry.CFG_VAL_0003 = struct(...
                'code', 'CFG-VAL-0003', ...
                'severity', 'WARN', ...
                'category', 'Parameter Validation', ...
                'description', 'CFL condition may be violated (stability warning)', ...
                'remediation', 'Reduce dt or increase grid spacing; check Parameters.dt', ...
                'causes', {{'dt too large for grid resolution', 'High velocity region'}});

            registry.CFG_VAL_0004 = struct(...
                'code', 'CFG-VAL-0004', ...
                'severity', 'ERROR', ...
                'category', 'Configuration', ...
                'description', 'Invalid initial condition type specified', ...
                'remediation', 'Choose from valid IC types in ic_factory.m', ...
                'causes', {{'Typo in ic_type', 'IC not implemented', 'Missing IC coefficients'}});

            registry.CFG_VAL_0005 = struct(...
                'code', 'CFG-VAL-0005', ...
                'severity', 'ERROR', ...
                'category', 'Configuration', ...
                'description', 'Method/mode combination not supported', ...
                'remediation', 'Check compatibility matrix in research.md (when created)', ...
                'causes', {{'Spectral/FV not fully implemented', 'Mode incompatible with method'}});

            % ===== UI-LAY: UI Layout =====
            registry.UI_LAY_0001 = struct(...
                'code', 'UI-LAY-0001', ...
                'severity', 'ERROR', ...
                'category', 'Layout', ...
                'description', 'UI component grid position out of bounds', ...
                'remediation', 'Check UI_Layout_Config.m row/column indices', ...
                'causes', {{'Layout.Row exceeds RowHeight array', 'Layout.Column exceeds ColumnWidth array'}});

            registry.UI_LAY_0002 = struct(...
                'code', 'UI-LAY-0002', ...
                'severity', 'WARN', ...
                'category', 'Layout', ...
                'description', 'Component uses Position instead of grid layout', ...
                'remediation', 'Replace Position with Layout.Row and Layout.Column', ...
                'causes', {{'Legacy code not refactored', 'Manual position override'}});

            % ===== UI-CB: UI Callbacks =====
            registry.UI_CB_0001 = struct(...
                'code', 'UI-CB-0001', ...
                'severity', 'ERROR', ...
                'category', 'Callback Error', ...
                'description', 'UI callback failed during execution', ...
                'remediation', 'Check callback function in UIController.m; see stack trace', ...
                'causes', {{'Invalid user input', 'Missing app property', 'Callback logic error'}});

            registry.UI_CB_0002 = struct(...
                'code', 'UI-CB-0002', ...
                'severity', 'WARN', ...
                'category', 'Callback', ...
                'description', 'Launch simulation called with invalid configuration', ...
                'remediation', 'Fix configuration errors in preflight validation panel', ...
                'causes', {{'Preflight checks failed', 'Missing required parameters'}});

            % ===== RUN-EXEC: Runner/Dispatcher =====
            registry.RUN_EXEC_0001 = struct(...
                'code', 'RUN-EXEC-0001', ...
                'severity', 'ERROR', ...
                'category', 'Dispatcher', ...
                'description', 'Unknown method specified in Run_Config', ...
                'remediation', ['Use valid method aliases (e.g., ''FD''/''Finite Difference'', ' ...
                                '''Spectral''/''FFT'', ''FV''/''Finite Volume'', ' ...
                                '''3D Spectral'', ''Placeholder'')'], ...
                'causes', {{'Typo in Run_Config.method', 'Method not implemented'}});

            registry.RUN_EXEC_0002 = struct(...
                'code', 'RUN-EXEC-0002', ...
                'severity', 'ERROR', ...
                'category', 'Dispatcher', ...
                'description', 'Unknown mode for specified method', ...
                'remediation', 'For FD: Evolution, Convergence, ParameterSweep, Plotting', ...
                'causes', {{'Typo in Run_Config.mode', 'Mode not implemented for method'}});

            registry.RUN_EXEC_0003 = struct(...
                'code', 'RUN-EXEC-0003', ...
                'severity', 'ERROR', ...
                'category', 'Execution', ...
                'description', 'Simulation failed during execution', ...
                'remediation', 'Check solver logs and parameters; see nested exception', ...
                'causes', {{'Numerical instability', 'Invalid parameters', 'Solver bug'}});

            % ===== SOL-FD: Finite Difference Solver =====
            registry.SOL_FD_0001 = struct(...
                'code', 'SOL-FD-0001', ...
                'severity', 'ERROR', ...
                'category', 'Solver Error', ...
                'description', 'FD solver encountered NaN or Inf values', ...
                'remediation', 'Check dt (reduce if necessary), check IC, check boundary conditions', ...
                'causes', {{'Numerical instability', 'dt too large', 'Invalid IC'}});

            registry.SOL_FD_0002 = struct(...
                'code', 'SOL-FD-0002', ...
                'severity', 'ERROR', ...
                'category', 'Solver Error', ...
                'description', 'Poisson solver failed to converge', ...
                'remediation', 'Check grid resolution, boundary conditions, or increase max iterations', ...
                'causes', {{'Bad boundary conditions', 'Singular system', 'Insufficient iterations'}});

            % ===== SOL-SP / SOL-FV / SOL-PL: Other Solvers =====
            registry.SOL_SP_0001 = struct(...
                'code', 'SOL-SP-0001', ...
                'severity', 'ERROR', ...
                'category', 'Not Implemented', ...
                'description', 'Spectral method not yet fully implemented', ...
                'remediation', 'Use FD method (''FD'') instead', ...
                'causes', {{'Spectral solver is stub', 'Feature not yet developed'}});

            registry.SOL_SP_0002 = struct(...
                'code', 'SOL-SP-0002', ...
                'severity', 'ERROR', ...
                'category', 'Not Implemented', ...
                'description', '3D Spectral method is registered but not implemented', ...
                'remediation', 'Use FD method (''FD'') until 3D spectral implementation is added', ...
                'causes', {{'3D spectral solver is placeholder', 'Feature planned but not developed'}});

            registry.SOL_FV_0001 = struct(...
                'code', 'SOL-FV-0001', ...
                'severity', 'ERROR', ...
                'category', 'Unsupported Workflow', ...
                'description', 'Finite Volume workflow is not enabled for the requested mode', ...
                'remediation', 'Use FV in Evolution mode, or switch to FD for Convergence/ParameterSweep', ...
                'causes', {{'FV Convergence is currently blocked', 'FV ParameterSweep is currently blocked'}});

            registry.SOL_SW_0001 = struct(...
                'code', 'SOL-SW-0001', ...
                'severity', 'ERROR', ...
                'category', 'Unsupported Workflow', ...
                'description', 'Shallow Water workflow is not enabled for the requested mode', ...
                'remediation', 'Use SWE in Evolution mode until convergence and sweep studies are expanded', ...
                'causes', {{'SWE Convergence is currently blocked', 'SWE ParameterSweep is currently blocked'}});

            registry.SOL_PL_0001 = struct(...
                'code', 'SOL-PL-0001', ...
                'severity', 'ERROR', ...
                'category', 'Placeholder Method', ...
                'description', 'Placeholder method selected in Run_Config', ...
                'remediation', 'Switch to a concrete method alias (for example ''FD'' or ''Finite Difference'')', ...
                'causes', {{'Placeholder selected intentionally', 'Method value left as TODO/TBD'}} );

            % ===== IO-FS: File I/O =====
            registry.IO_FS_0001 = struct(...
                'code', 'IO-FS-0001', ...
                'severity', 'ERROR', ...
                'category', 'File I/O', ...
                'description', 'Failed to create output directory', ...
                'remediation', 'Check disk space and write permissions; ensure Data/ exists', ...
                'causes', {{'No write permission', 'Disk full', 'Invalid path'}});

            registry.IO_FS_0002 = struct(...
                'code', 'IO-FS-0002', ...
                'severity', 'ERROR', ...
                'category', 'File I/O', ...
                'description', 'Failed to save output file (MAT, figure, report)', ...
                'remediation', 'Check disk space and write permissions', ...
                'causes', {{'Disk full', 'No permission', 'File locked by another process'}});

            registry.IO_FS_0003 = struct(...
                'code', 'IO-FS-0003', ...
                'severity', 'WARN', ...
                'category', 'File I/O', ...
                'description', 'Failed to load previous run data (Plotting mode)', ...
                'remediation', 'Check run_id exists in Data/Output/; verify .mat file integrity', ...
                'causes', {{'run_id not found', 'Corrupted .mat file', 'Wrong directory'}});

            % ===== MON-SUS: Sustainability Monitors =====
            registry.MON_SUS_0001 = struct(...
                'code', 'MON-SUS-0001', ...
                'severity', 'WARN', ...
                'category', 'Monitor', ...
                'description', 'Hardware monitor bridge unavailable', ...
                'remediation', 'Install LibreHardwareMonitor or disable sustainability monitoring', ...
                'causes', {{'LibreHardwareMonitor not installed', 'Service not running'}});

            registry.MON_SUS_0002 = struct(...
                'code', 'MON-SUS-0002', ...
                'severity', 'WARN', ...
                'category', 'Monitor', ...
                'description', 'iCUE bridge unavailable', ...
                'remediation', 'Install iCUE software or disable iCUE integration', ...
                'causes', {{'iCUE not installed', 'iCUE API not accessible'}});

            % ===== TST: Testing Framework =====
            registry.TST_0001 = struct(...
                'code', 'TST-0001', ...
                'severity', 'ERROR', ...
                'category', 'Test Failure', ...
                'description', 'Test case failed to execute', ...
                'remediation', 'Check test configuration and dependencies', ...
                'causes', {{'Invalid test parameters', 'Missing test data', 'Test bug'}});

            registry.TST_0002 = struct(...
                'code', 'TST-0002', ...
                'severity', 'ERROR', ...
                'category', 'Test Harness', ...
                'description', 'Test harness infrastructure error', ...
                'remediation', 'Check Run_All_Tests.m and test helper functions', ...
                'causes', {{'Missing Test_Cases function', 'Path issue', 'Harness bug'}});

            % ===== GEN: Generic =====
            registry.GEN_0001 = struct(...
                'code', 'GEN-0001', ...
                'severity', 'ERROR', ...
                'category', 'Generic Error', ...
                'description', 'Unclassified error occurred', ...
                'remediation', 'See error message and stack trace for details', ...
                'causes', {{'Error type not yet categorized', 'Unexpected condition'}});
        end
    end
end
