function labels = resolve_analysis_plot_labels(analysis)
% resolve_analysis_plot_labels Resolve method-aware labels for results plots.

    labels = struct( ...
        'primary_title', '\omega', ...
        'primary_name', 'Vorticity', ...
        'primary_symbol', '\omega', ...
        'secondary_title', '\psi', ...
        'secondary_name', 'Streamfunction', ...
        'secondary_symbol', '\psi', ...
        'snapshot_title_base', 'Vorticity Evolution', ...
        'contour_title_base', 'Vorticity + \psi contours', ...
        'vector_title_base', 'Vector field', ...
        'streamline_title_base', 'Streamlines only', ...
        'streamfunction_title_base', 'Streamfunction \psi', ...
        'speed_title_base', 'Speed |u|', ...
        'wall_omega_title_base', 'Auxiliary wall vorticity \omega_w', ...
        'gallery_evolution_title', 'Finite-difference vorticity evolution \omega(x,y,t)', ...
        'gallery_secondary_title', 'Streamfunction evolution \psi(x,y,t)', ...
        'gallery_speed_title', 'Instantaneous velocity magnitude', ...
        'gallery_vector_title', 'Velocity vector-field evolution', ...
        'gallery_contour_title', 'Vorticity + streamfunction contours', ...
        'gallery_streamline_title', 'Streamline snapshots', ...
        'gallery_wall_omega_title', 'Auxiliary wall-vorticity snapshots (discrete wall-shear closure)', ...
        'diagnostics_title', 'Integral diagnostics', ...
        'diagnostics_primary', 'Kinetic energy', ...
        'diagnostics_secondary', 'Enstrophy', ...
        'peak_title', 'Peak vorticity decay', ...
        'peak_ylabel', 'max|\omega|');

    if nargin < 1 || ~isstruct(analysis)
        return;
    end

    method_family = '';
    if isfield(analysis, 'method_family') && ~isempty(analysis.method_family)
        method_family = lower(char(string(analysis.method_family)));
    elseif isfield(analysis, 'method') && ~isempty(analysis.method)
        method_family = lower(char(string(analysis.method)));
    end

    if contains(method_family, 'shallow_water') || contains(method_family, 'swe')
        labels.primary_title = '\eta';
        labels.primary_name = 'Free-surface elevation';
        labels.primary_symbol = '\eta';
        labels.secondary_title = 'h';
        labels.secondary_name = 'Water depth';
        labels.secondary_symbol = 'h';
        labels.snapshot_title_base = 'Free-surface evolution';
        labels.contour_title_base = '\eta + h contours';
        labels.vector_title_base = 'Depth-averaged velocity';
        labels.streamline_title_base = 'Depth-averaged streamlines';
        labels.streamfunction_title_base = 'Water depth h';
        labels.speed_title_base = 'Depth-averaged speed';
        labels.gallery_evolution_title = 'Free-surface elevation \eta(x,y,t)';
        labels.gallery_secondary_title = 'Water-depth evolution h(x,y,t)';
        labels.gallery_speed_title = 'Depth-averaged velocity magnitude';
        labels.gallery_vector_title = 'Depth-averaged velocity vector field';
        labels.gallery_contour_title = 'Free-surface elevation + depth contours';
        labels.gallery_streamline_title = 'Depth-averaged streamline snapshots';
        labels.diagnostics_title = 'Shallow-water diagnostics';
        labels.diagnostics_primary = 'Total energy';
        labels.diagnostics_secondary = 'Surface variance';
        labels.peak_title = 'Peak free-surface elevation';
        labels.peak_ylabel = 'max|\eta|';
    end
end
