function params = create_default_parameters()
% CREATE_DEFAULT_PARAMETERS Factory for canonical simulation defaults
%
% This function returns a single `params` struct containing all runtime
% and UI-default values used throughout the analysis framework. It is the
% authoritative source of default values for solver configuration, I/O,
% visualization, experiment sweeps and UI controls. Callers may modify
% individual fields after construction to override defaults.
%
% Key categories populated in `params`:
%  - numerical & grid settings: Nx, Ny, dt, t_final, etc.
%  - initial condition (IC) settings: ic_type, ic_coeff*, ic_ui_catalog
%  - runtime/method settings: method, analysis_method, method_config
%  - I/O & media: save_csv, animation settings, media fallbacks
%  - monitoring & sustainability: energy_monitoring, collectors
%  - UI-related defaults: visualization, plot_settings, ic_ui_catalog
%
% Usage:
%   params = create_default_parameters();
%   % override a few values
%   params.Nx = 256;
%   params.ic_type = 'vortex_blob_gaussian';
%
% Developer notes:
%  - `ic_ui_catalog` and `ic_scenario_catalog` are constructed by helper
%    functions within this file and describe UI field metadata. See
%    `make_ic_entry`, `make_dyn_field`, `make_shared_flags`,
%    and `make_ic_scenario` for descriptor details.
%  - A small debug inspector `debug_ic_catalog` is provided to print a
%    summary of these catalogs for quick runtime inspection.
%
% Returns:
%   params - Struct with default simulation parameters
%

default_stretched_dyn = create_default_stretched_gaussian_dynamic_values();
default_reference_scale = default_calibrated_stretched_scale();
default_reference_nu = default_calibrated_stretched_nu();

params = struct(...
    'default_method', 'FD', ...
    'default_mode', 'Evolution', ...
    'output_root', 'Results', ...
    'Lx', 10, ...
    'Ly', 10, ...
    'Nx', 128, ...
    'Ny', 128, ...
    'Nz', 12, ...
    'Lz', 1.0, ...
    'grid_mode', 'domain_driven', ...
    'dx', 2, ...
    'dy', 2, ...
    'is_anisotropic', false, ...
    'delta', 2, ...
    'use_explicit_delta', true, ...
    'nu', default_reference_nu, ...
    'dt', 0.01, ...
    'Tfinal', 8, ...
    't_final', 8, ...
    'num_plot_snapshots', 9, ...
    'num_snapshots', 9, ...
    'ic_type', "stretched_gaussian", ...
    'ic_coeff', [default_stretched_dyn.stretch_x, default_stretched_dyn.stretch_y, default_reference_scale, 0.0], ...
    'ic_amplitude', 1.0, ...
    'fd_post_closure_edge_omega_zero', false, ...
    'use_arakawa', false, ...
    'use_gpu', true, ...
    'cpu_allocation_pct', 80, ...
    'memory_allocation_pct', 70, ...
    'gpu_allocation_pct', 80, ...
    'monitor_update_hz', 2, ...
    'progress_update_hz', 6, ...
    'pool_workers', 2, ...
    'resource_strategy', 'mode_adaptive', ...
    'gpu_policy', 'auto', ...
    'planner_use_host_profiles', true, ...
    'interactive_pool_workers_max', 2, ...
    'throughput_pool_workers_min', 2, ...
    'interactive_thread_headroom_pct', 75, ...
    'gpu_min_workload_cells_steps', 0, ...
    'gpu_memory_guard_pct', 80, ...
    'pool_workers_max_override', 0, ...
    'bc_case', 'periodic', ...
    'boundary_condition_case', 'periodic', ...
    'bc_top', 'Periodic', ...
    'bc_bottom', 'Periodic', ...
    'bc_left', 'Periodic', ...
    'bc_right', 'Periodic', ...
    'bc_top_math', 'periodic', ...
    'bc_bottom_math', 'periodic', ...
    'bc_left_math', 'periodic', ...
    'bc_right_math', 'periodic', ...
    'bc_top_physical', 'periodic', ...
    'bc_bottom_physical', 'periodic', ...
    'bc_left_physical', 'periodic', ...
    'bc_right_physical', 'periodic', ...
    'U_top', 0.0, ...
    'U_bottom', 0.0, ...
    'U_left', 0.0, ...
    'U_right', 0.0, ...
    'analysis_method', "Finite Difference", ...
    'method', "finite_difference", ...
    'method_config', [], ...
    'mode', "solve", ...
    'live_preview', false, ...
    'progress_stride', 0, ...
    'live_stride', 0, ...
    'create_animations', true, ...
    'animation_format', 'mp4+gif', ...
    'animation_export_format', 'mp4+gif', ...
    'animation_export_formats', {{'mp4', 'gif'}}, ...
    'animation_fps', 30, ...
    'animation_quality', 90, ...
    'animation_duration_s', 10, ...
    'animation_gif_min_frames', 2, ...
    'animation_export_dpi', 600, ...
    'animation_export_preset', 'double_column_report', ...
    'animation_export_width_in', 7.16, ...
    'animation_export_height_in', 5.37, ...
    'animation_export_resolution_px', [4296, 3222], ...
    'animation_num_frames', 100, ...
    'num_animation_frames', 100, ...
    'animation_codec', 'MPEG-4', ...
    'animation_dir', [], ...
    'plot_trim_layers', 1, ...
    'plot_limit_mode', 'trimmed_interior_extrema', ...
    'plot_percentile_band', [1, 99], ...
    'plot_include_boundary_diagnostics', false, ...
    'media', struct( ...
    'format', 'mp4+gif', ...
    'formats', {{'mp4', 'gif'}}, ...
    'codec', 'MPEG-4', ...
    'fps', 30, ...
    'duration_s', 10, ...
    'num_frames', 100, ...
    'gif_min_frame_count', 2, ...
    'quality', 90, ...
    'dpi', 600, ...
    'preset', 'double_column_report', ...
    'width_in', 7.16, ...
    'height_in', 5.37, ...
    'resolution_px', [4296, 3222]), ...
    'reporting', struct( ...
    'template', 'default', ...
    'template_by_mode', struct( ...
    'Evolution', 'evolution', ...
    'Convergence', 'convergence', ...
    'ParameterSweep', 'parameter_sweep', ...
    'Plotting', 'plotting')), ...
    'bathymetry_enabled', false, ...
    'bathymetry_file', '', ...
    'bathymetry_resolution', 96, ...
    'bathymetry_use_dry_mask', true, ...
    'bathymetry_dimension_policy', 'by_method', ...
    'bathymetry_scenario', 'flat_2d', ...
    'bathymetry_bed_slope', 0.03, ...
    'bathymetry_depth_offset', 1000.0, ...
    'bathymetry_relief_amplitude', 180.0, ...
    'energy_monitoring', struct('enabled', true, 'sample_interval', 0.5, 'output_dir', '../../sensor_logs'), ...
    'sustainability', struct( ...
    'enabled', true, ...
    'build_model', false, ...
    'auto_compare', false, ...
    'sample_interval', 0.5, ...
    'machine_tag', 'auto', ...
    'environmental_model', struct( ...
    'electricity_scope', 'consumed_location_based', ...
    'grid_carbon_intensity_kgco2e_per_kwh', 0.19553, ...
    'grid_carbon_intensity_gco2e_per_kwh', 195.53, ...
    'factor_year', 2025, ...
    'factor_region', 'UK', ...
    'factor_source_tag', 'uk_gov_2025_consumed_2023data', ...
    'factor_source_url', 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025', ...
    'line_losses_included', true, ...
    'allow_component_power_sum_fallback', true, ...
    'detect_apu_power_duplication', true), ...
    'collector_paths', struct('hwinfo', '', 'icue', ''), ...
    'collector_runtime', struct( ...
    'session_output_dir', '', ...
    'session_csv_path', '', ...
    'collector_launch_root_dir', '', ...
    'collector_launch_csv_file', 'launch_telemetry.csv', ...
    'hwinfo_shared_memory_blob_path', '', ...
    'hwinfo_control_mode', 'pro_cli_csv', ...
    'hwinfo_pro_cli_enabled', true, ...
    'hwinfo_pro_log_write_direct', true, ...
    'hwinfo_pro_poll_rate_ms', 1000, ...
    'hwinfo_pro_launch_timeout_s', 20, ...
    'hwinfo_pro_csv_timeout_s', 45, ...
    'hwinfo_pro_force_stop_fallback', true, ...
    'hwinfo_pro_csv_path', '', ...
    'hwinfo_transport_mode', 'auto', ...
    'hwinfo_csv_target_dir', '', ...
    'hwinfo_csv_target_path', '', ...
    'hwinfo_csv_dir', '', ...
    'hwinfo_csv_path', '', ...
    'icue_csv_dir', '', ...
    'icue_csv_path', '', ...
    'icue_user_props_path', '', ...
    'icue_config_path', '', ...
    'icue_devices_path', '')));

% UI / runtime defaults
% These values are migrated from the legacy UIController.ui_defaults so
% that the factory function remains the single source of truth. They
% influence both what the UI shows (form labels, toggles) and the
% behaviour of the runtime (save flags, figure DPI, convergence rules).
params.time_integrator = 'RK4';
params.equal_spacing = false;
params.save_csv = true;
params.save_mat = false;
params.save_json = false;
params.save_reports = false;
params.figures_save_png = false;
params.figures_save_fig = true;
params.figures_dpi = 600;
params.figures_close_after_save = false;
params.figures_use_owl_saver = true;
params.convergence_N_coarse = 64;
params.convergence_N_max = 873;
params.convergence_dt_values = [0.04, 0.02, 0.01];
params.convergence_tol = 1e-1;
params.convergence_criterion_type = 'successive_vorticity_relative_l2';
params.convergence_binary = true;
params.convergence_use_adaptive = false;
params.convergence_max_jumps = 5;
params.convergence_agent_enabled = false;
params.convergence = struct();
params.convergence.dispatch = struct( ...
    'strategy', 'standard', ...         % standard | agent_guided
    'progress_telemetry', true, ...
    'artifact_verbosity', 'normal', ...
    'reuse_cache', true);
params.convergence.study = struct( ...
    'N_coarse', params.convergence_N_coarse, ...
    'N_max', params.convergence_N_max, ...
    'verification_case', '', ...
    'tolerance', params.convergence_tol, ...
    'criterion_type', params.convergence_criterion_type, ...
    'binary_search', params.convergence_binary, ...
    'use_adaptive', params.convergence_use_adaptive, ...
    'max_jumps', params.convergence_max_jumps, ...
    'temporal', struct( ...
    'dt_values', params.convergence_dt_values, ...
    'fine_N', params.convergence_N_max), ...
    'spatial', struct( ...
    'N_values', [], ...
    'Nz_fixed', params.Nz), ...
    'modal', struct( ...
    'N_values', []), ...
    'reference', struct( ...
    'preferred_strategy', '', ...
    'allow_self_reference', true, ...
    'refinement_multiplier', 2.0), ...
    'verdict', struct( ...
    'monotonicity_relaxation', 0.05, ...
    'minimum_improvement_factor', 1.05));
params.convergence.agent = struct( ...
    'enabled', params.convergence_agent_enabled, ...
    'objective_mode', 'balanced', ...
    'objective_weights', struct('accuracy', 0.5, 'wall_time', 0.25, 'energy', 0.25), ...
    'stopping_strictness', 'standard', ...
    'preflight_depth', 'normal', ...
    'exploration_aggressiveness', 'medium');
params.mesh_convergence = struct( ...
    'enabled', true, ...
    'ic_preset_id', 'elliptical_vortex', ...
    'use_converged_mesh_seed', false, ...
    'allow_unconverged_mesh_fallback', true, ...
    'force_bc_case', 'periodic', ...
    'force_bathymetry', 'flat_2d', ...
    'methods', {{'FD', 'Spectral'}}, ...
    'mesh_start_equal_xy', true, ...
    'mesh_start_n', 32, ...
    'mesh_start_nx', 32, ...
    'mesh_start_ny', 32, ...
    'mesh_final_equal_xy', true, ...
    'mesh_final_n', 873, ...
    'mesh_final_nx', 873, ...
    'mesh_final_ny', 873, ...
    'mesh_level_count', 9, ...
    'mesh_spacing_level_count', 9, ...
    'required_mesh_levels', [], ...
    'mesh_ladder_mode', 'bounded', ...
    'mesh_powers_of_two_max_n', 1024, ...
    'convergence_tolerance', 1.0, ...
    'convergence_mesh_levels_fd', [32, 137, 242, 347, 453, 558, 663, 768, 873], ...
    'convergence_mesh_levels_spectral', [32, 137, 242, 347, 453, 558, 663, 768, 873], ...
    'mesh_selection_policy', 'first_converged_or_finest_mesh', ...
    'adaptive_timestep', struct( ...
    'enabled', false, ...
    'C_adv', 0.5, ...
    'C_diff', 0.25), ...
    'snapshot_storage_precision', 'single', ...
    'store_velocity_snapshot_cubes', false, ...
    'store_native_velocity_snapshots', false, ...
    'stability_scope', 'observed_cfl', ...
    'save_figures', true, ...
    'save_level_visuals', true, ...
    'save_json', params.save_json, ...
    'save_reports', params.save_reports, ...
    'create_animations', false, ...
    'num_plot_snapshots', params.num_plot_snapshots, ...
    'resource_strategy', 'throughput_first');
params.phase1 = struct( ...
    'enabled', true, ...
    'use_converged_mesh_seed', false, ...
    'allow_unconverged_mesh_fallback', true, ...
    'force_bc_case', 'periodic', ...
    'force_bathymetry', 'flat_2d', ...
    'methods', {{'FD', 'Spectral'}}, ...
    'fd_grid_n', 558, ...
    'fd_dt', 0.006, ...
    'spectral_grid_n', 873, ...
    'spectral_dt', 0.0038, ...
    'taylor_green_fd_grid_n', 558, ...
    'taylor_green_spectral_grid_n', 873, ...
    'taylor_green_fd_dt', 0.001, ...
    'taylor_green_spectral_dt', 0.001, ...
    'taylor_green_honor_fixed_dt', true, ...
    'mesh_start_equal_xy', true, ...
    'mesh_start_n', 32, ...
    'mesh_start_nx', 32, ...
    'mesh_start_ny', 32, ...
    'mesh_final_equal_xy', true, ...
    'mesh_final_n', 768, ...
    'mesh_final_nx', 768, ...
    'mesh_final_ny', 768, ...
    'mesh_level_count', 7, ...
    'mesh_ladder_mode', 'bounded', ...
    'mesh_powers_of_two_max_n', 1024, ...
    'convergence_tolerance', 1.0, ...
    'convergence_mesh_levels_fd', [32, 155, 277, 400, 523, 645, 768], ...
    'convergence_mesh_levels_spectral', [32, 155, 277, 400, 523, 645, 768], ...
    'mesh_selection_policy', 'first_converged_or_finest_mesh', ...
    'adaptive_timestep', struct( ...
    'enabled', false, ...
    'C_adv', 0.5, ...
    'C_diff', 0.25), ...
    'stability_scope', 'observed_cfl', ...
    'save_figures', true, ...
    'create_animations', true, ...
    'workflow_animation_panes', {{'evolution', 'streamfunction', 'speed', 'vector', 'contour'}}, ...
    'num_plot_snapshots', params.num_plot_snapshots, ...
    'resource_strategy', 'throughput_first');
params.phase2 = struct( ...
    'enabled', true, ...
    'save_figures', true, ...
    'create_animations', true, ...
    'num_plot_snapshots', params.num_plot_snapshots, ...
    'resource_strategy', 'throughput_first', ...
    'fd_first_only', true, ...
    'fd_grid_n', 558, ...
    'fd_dt', params.dt, ...
    'taylor_green_fd_grid_n', 558, ...
    'taylor_green_fd_dt', 0.001, ...
    'taylor_green_spectral_dt', 0.001, ...
    'taylor_green_honor_fixed_dt', true, ...
    'adaptive_timestep', struct( ...
        'enabled', false, ...
        'C_adv', 0.5, ...
    'C_diff', 0.25), ...
    'boundary_nu_floor', 1.0e-2, ...
    'boundary_dt_max', inf, ...
    'methods', {{'FD'}}, ...
    'ic_cases', [ ...
    struct( ...
    'id', 'elliptical_vortex', ...
    'label', 'Calibrated Elliptic Gaussian', ...
    'ic_type', 'elliptical_vortex', ...
    'tfinal_s', NaN), ...
    struct( ...
    'id', 'taylor_green', ...
    'label', 'Taylor-Green', ...
    'ic_type', 'taylor_green', ...
    'tfinal_s', NaN) ...
    ], ...
    'taylor_green_runtime_overrides', create_default_taylor_green_runtime_overrides(params), ...
    'no_initial_condition_tfinal', 60.0, ...
    'boundary_visual_crop_cells', 1, ...
    'contour_levels', 36, ...
    'workflow_animation_panes', {{'evolution', 'streamfunction', 'speed', 'vector', 'contour'}}, ...
    'scenarios', [ ...
    struct( ...
    'id', 'lid_driven_cavity', ...
    'label', 'Enclosed Driven Cavity', ...
    'top_speed_mps', 0.5, ...
    'bottom_speed_mps', 0.0, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0), ...
    struct( ...
    'id', 'driven_channel_flow', ...
    'label', 'Driven Channel Flow', ...
    'top_speed_mps', 0.5, ...
    'bottom_speed_mps', 0.0, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0), ...
    struct( ...
    'id', 'enclosed_shear_layer', ...
    'label', 'Enclosed Shear Layer', ...
    'top_speed_mps', 0.5, ...
    'bottom_speed_mps', -0.5, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0) ...
    ]);
params.phase3 = struct( ...
    'enabled', true, ...
    'save_figures', true, ...
    'create_animations', false, ...
    'num_plot_snapshots', params.num_plot_snapshots, ...
    'resource_strategy', 'throughput_first', ...
    'methods', {{'FD', 'Spectral'}}, ...
    'domain_equal_mesh', logical(params.Nx == params.Ny), ...
    'domain_nx', params.Nx, ...
    'domain_ny', params.Ny, ...
    'domain_lx', params.Lx, ...
    'domain_ly', params.Ly, ...
    'scenarios', [ ...
    struct( ...
    'id', 'simple_default_bathymetry', ...
    'label', 'Simple Default Bathymetry', ...
    'bc_id', 'enclosed_shear_layer', ...
    'bc_label', 'Enclosed Shear Layer', ...
    'bathymetry_id', 'flat_2d', ...
    'bathymetry_label', 'Flat', ...
    'top_speed_mps', 10.0, ...
    'bottom_speed_mps', -10.0, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0, ...
    'bathymetry_state', struct()), ...
    struct( ...
    'id', 'tsunami_runup_composite', ...
    'label', 'Composite Tsunami Run-up Bathymetry', ...
    'bc_id', 'enclosed_shear_layer', ...
    'bc_label', 'Enclosed Shear Layer', ...
    'bathymetry_id', 'tsunami_runup_composite_2d', ...
    'bathymetry_label', 'Composite Tsunami Run-up', ...
    'top_speed_mps', 15.0, ...
    'bottom_speed_mps', -15.0, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0, ...
    'bathymetry_state', struct()), ...
    struct( ...
    'id', 'tohoku_profile', ...
    'label', 'Tohoku Profile Bathymetry', ...
    'bc_id', 'enclosed_shear_layer', ...
    'bc_label', 'Enclosed Shear Layer', ...
    'bathymetry_id', 'tohoku_profile_2d', ...
    'bathymetry_label', 'Tohoku Profile', ...
    'top_speed_mps', 20.0, ...
    'bottom_speed_mps', -20.0, ...
    'left_speed_mps', 0.0, ...
    'right_speed_mps', 0.0, ...
    'bathymetry_state', struct()) ...
    ]);
params.reference_calibration_presets = create_reference_gaussian_preset_defaults(params);
params = apply_default_ic_runtime_snapshot(params, params.reference_calibration_presets.elliptical_vortex.runtime_overrides);
params.mesh_convergence.ic_snapshot = params.reference_calibration_presets.elliptical_vortex.runtime_overrides;
params.phase1.ic_snapshot = struct();
params.phase1.ic_study = create_phase1_ic_study_config(params);
params.enable_monitoring = true;
params.launch_progress_only = false;
params.sample_interval = 0.5;
params.sustainability.sample_interval = params.sample_interval;
params.sustainability_auto_log = true;
params.collector_hwinfo = false;
params.collector_icue = false;
params.collector_strict = false;
params.machine_tag = getenv('COMPUTERNAME');
params.collector_machine_profiles = create_collector_machine_profiles();
params.collector_machine_profile = resolve_collector_machine_profile( ...
    params.machine_tag, params.collector_machine_profiles);
params.collector_panel_profile = resolve_collector_panel_profile( ...
    params.collector_machine_profile);
params.collector_launch_root_dir = '';
params.collector_launch_csv_file = 'launch_telemetry.csv';
params.hwinfo_csv_target_dir = '';
params.hwinfo_csv_target_path = '';
params.hwinfo_control_mode = 'pro_cli_csv';
params.sustainability.machine_profile = params.collector_machine_profile;
params.sustainability.collector_panel_profile = params.collector_panel_profile;
existing_environmental_model = struct();
if isfield(params, 'sustainability') && isstruct(params.sustainability) && ...
        isfield(params.sustainability, 'environmental_model') && isstruct(params.sustainability.environmental_model)
    existing_environmental_model = params.sustainability.environmental_model;
end
params.sustainability.environmental_model = merge_structs( ...
    struct( ...
        'electricity_scope', 'consumed_location_based', ...
        'grid_carbon_intensity_kgco2e_per_kwh', 0.19553, ...
        'grid_carbon_intensity_gco2e_per_kwh', 195.53, ...
        'factor_year', 2025, ...
        'factor_region', 'UK', ...
        'factor_source_tag', 'uk_gov_2025_consumed_2023data', ...
        'factor_source_url', 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025', ...
        'line_losses_included', true, ...
        'allow_component_power_sum_fallback', true, ...
        'detect_apu_power_duplication', true), ...
    existing_environmental_model);
params.sustainability.collector_runtime.collector_launch_root_dir = params.collector_launch_root_dir;
params.sustainability.collector_runtime.collector_launch_csv_file = params.collector_launch_csv_file;
params.sustainability.collector_runtime.hwinfo_csv_target_dir = params.hwinfo_csv_target_dir;
params.sustainability.collector_runtime.hwinfo_csv_target_path = params.hwinfo_csv_target_path;
params.sustainability.collector_runtime.hwinfo_control_mode = params.hwinfo_control_mode;
params.sustainability.collector_runtime.hwinfo_pro_cli_enabled = true;
params.sustainability.collector_runtime.hwinfo_pro_log_write_direct = true;
params.sustainability.collector_runtime.hwinfo_pro_poll_rate_ms = 1000;
params.sustainability.collector_runtime.hwinfo_pro_launch_timeout_s = 20;
params.sustainability.collector_runtime.hwinfo_pro_csv_timeout_s = 45;
params.sustainability.collector_runtime.hwinfo_pro_force_stop_fallback = true;
params.sustainability.collector_runtime.hwinfo_pro_csv_path = '';
params.sustainability.collector_runtime.collector_panel_profile = params.collector_panel_profile;
params.collectors = struct( ...
    'hwinfo', params.collector_hwinfo, ...
    'icue', params.collector_icue, ...
    'strict', params.collector_strict, ...
    'machine_tag', params.machine_tag, ...
    'machine_profile', params.collector_machine_profile, ...
    'panel_profile', params.collector_panel_profile);
params.motion_enabled = false;
params.motion_model = 'none';
params.motion_amplitude = 0.0;
params.run_mode_internal = 'Evolution';
params.simulation_scenario = 'Manual';
params.simulation_scenario_catalog = create_simulation_scenario_catalog();
params.bathymetry_scenario_catalog_2d = create_bathymetry_scenario_catalog_2d();
params.bathymetry_scenario_catalog_3d = create_bathymetry_scenario_catalog_3d();
params.bathymetry_custom_points = create_default_bathymetry_control_points(params.Lx, params.Ly);
params.bathymetry_dynamic_params = create_default_bathymetry_dynamic_params( ...
    params.bathymetry_scenario_catalog_2d, params.bathymetry_scenario_catalog_3d, params);
params.ic_pattern = 'single';
params.ic_arrangement = params.ic_pattern;
params.ic_scale = default_reference_scale;
params.ic_scenario = 'Manual';
params.ic_count = 1;
params.ic_contour_bands = false;
params.ic_multi_vortex_experimental = false;
params.ic_multi_vortex_rows = create_default_multi_vortex_rows();
params.ic_dynamic_values = default_stretched_dyn;
params.ic_coeff1 = default_stretched_dyn.stretch_x;
params.ic_coeff2 = default_stretched_dyn.stretch_y;
params.ic_coeff3 = default_reference_scale;
params.ic_coeff4 = 0.0;
params.ic_center_x = 0.0;
params.ic_center_y = 0.0;
params.ic_ui_schema_version = 3;
params.ic_ui_catalog = create_ic_ui_catalog();
params.ic_scenario_catalog = create_ic_scenario_catalog(params.reference_calibration_presets);
params.ic_arrangement_catalog = create_ic_arrangement_catalog();
params.ic_arrangement_items = {params.ic_arrangement_catalog.id};
params.ic_multi_vortex_schema_version = 3;
params.ic_multi_vortex_defaults = create_ic_multi_vortex_defaults();
params.sweep_parameter = 'nu';
params.sweep_values = [1e-6, 5e-6, 1e-5];
params.experimentation = struct( ...
    'coeff_selector', 'ic_coeff1', ...
    'range_start', 0.5, ...
    'range_end', 2.0, ...
    'num_points', 4);

% Post-process derived fields
% Some runtime fields are derived from base values to keep the
% external API simple (e.g. Tfinal is the canonical source while
% t_final is provided as a convenience alias). Derived values are
% computed here so that downstream code can rely on their presence.
params.t_final = params.Tfinal;
params.num_snapshots = params.num_plot_snapshots;
params.snap_times = linspace(0, params.Tfinal, params.num_plot_snapshots);
params.plot_snap_times = params.snap_times;
params.animation_times = linspace(0, params.Tfinal, params.num_animation_frames);

% Ensure method and analysis_method are consistent
if isstring(params.method) || ischar(params.method)
    method_lower = lower(char(params.method));
    switch method_lower
        case {'fd', 'finite_difference', 'finite difference'}
            params.method = 'finite_difference';
            params.analysis_method = 'Finite Difference';
        case {'spectral', 'fft', 'pseudospectral'}
            params.method = 'spectral';
            params.analysis_method = 'Spectral';
        case {'fv', 'finite_volume'}
            params.method = 'finite_volume';
            params.analysis_method = 'Finite Volume';
        case {'swe', 'shallow_water', 'shallow water', 'shallowwater'}
            params.method = 'shallow_water';
            params.analysis_method = 'Shallow Water';
        case {'bathymetry', 'variable_bathymetry'}
            params.method = 'bathymetry';
            params.analysis_method = 'Variable Bathymetry';
        otherwise
            params.method = 'finite_difference';  % Default
            params.analysis_method = 'Finite Difference';
    end
end

% Method configuration defaults (self-contained, no external driver dependency)
params.method_config = struct();
params.method_config.fd = struct('advection_scheme', 'SparseMatrix', 'time_integrator', 'RK4');
params.method_config.spectral = struct('dealiasing_rule', '2/3', 'time_integrator', 'RK4');
params.method_config.fv = struct('reconstruction', 'MUSCL', 'flux', 'Roe', 'time_integrator', 'RK3');
params.method_config.fv3d = struct('vertical_diffusivity_scale', 1.0, 'z_boundary', 'no_flux');
params.method_config.swe2d = struct( ...
    'gravity', 9.81, ...
    'base_depth', 1.0, ...
    'dry_tolerance', 1.0e-4, ...
    'cfl', 0.45, ...
    'bed_relief_fraction', 1.15, ...
    'bed_friction_coeff', 0.015, ...
    'enable_wind', false, ...
    'wind_velocity_x', 0.0, ...
    'wind_velocity_y', 0.0, ...
    'wind_drag_coeff', 1.5e-3, ...
    'air_density', 1.225, ...
    'water_density', 1000.0, ...
    'initial_condition', 'lake_at_rest', ...
    'surface_amplitude', 0.08, ...
    'surface_sigma_x', 0.9, ...
    'surface_sigma_y', 0.6, ...
    'surface_center_x', -3.5, ...
    'surface_center_y', 0.0, ...
    'momentum_amplitude_x', 0.0, ...
    'momentum_amplitude_y', 0.0, ...
    'time_integrator', 'RK3');

% Default animation_dir is resolved at runtime to canonical run Media path.
params.animation_dir = '';

% Visualization defaults - helper functions
if exist('create_visualization_settings', 'file') == 2
    params.visualization = create_visualization_settings();
    params.plot_settings = create_plot_settings(params.visualization);
end
params.results_plot_scaling = struct( ...
    'trim_layers', params.plot_trim_layers, ...
    'limit_mode', params.plot_limit_mode, ...
    'percentile_band', params.plot_percentile_band, ...
    'include_boundary_diagnostics', params.plot_include_boundary_diagnostics);
if exist('create_boundary_condition_cases', 'file') == 2
    params.Default_Boundary_Condition = create_boundary_condition_cases();
end
end

function vis = create_visualization_settings()
% Default visualization settings
vis = struct(...
    'contour_method', "contourf", ...
    'contour_levels', 25, ...
    'contour_colormap', "gray", ...
    'vector_method', "quiver", ...
    'vector_subsampling', 4, ...
    'vector_scale', 1.0, ...
    'colormap', "turbo");
end

function plot_set = create_plot_settings(visualization)
% Default plot formatting settings
plot_set = struct(...
    'LineWidth', 1.5, ...
    'FontSize', 12, ...
    'MarkerSize', 8, ...
    'AxisLineWidth', 2.0, ...
    'ColorOrder', lines(7), ...
    'Grid', 'on', ...
    'Box', 'on', ...
    'Interpreter', 'latex', ...
    'Colormap', visualization.colormap);
end

function Default_Boundary_Condition = create_boundary_condition_cases()
% Default boundary condition case is pure periodic wherein the top surface is equal to the bottom surface and the left and right surfaces are equal. However, we also will define 4 other cases in different environments. These are found in the Boundary_Condition_Cases function.
Default_Boundary_Condition = struct('type', 'periodic', 'description', 'Pure periodic boundaries on all sides');
end

function catalog = create_ic_ui_catalog()
% Canonical UI schema for IC-specific controls and descriptors.
default_stretched_dyn = create_default_stretched_gaussian_dynamic_values();
default_elliptic_dyn = create_default_elliptical_dynamic_values();
catalog = [
    make_ic_entry( ...
    'no_initial_condition', 'No Initial Condition', ...
    '\omega(x,y,0)=0', ...
    {'where:', 'The initial vorticity field is identically zero.', 'Boundary forcing and evolution generate the flow thereafter.'}, ...
    struct([]), ...
    make_shared_flags(false, false, false, false, false), ...
    'no_initial_condition');

    make_ic_entry( ...
    'stretched_gaussian', 'Stretched Gaussian', ...
    '\omega(x,y)=\exp\left(-a(x-x_0)^2-b(y-y_0)^2\right)', ...
    {'where:', 'a,b in [0.1,10] control anisotropic stretch', 'x0,y0 shift vortex center', 'Amplitude rescales peak without changing stretch'}, ...
    [ ...
    make_dyn_field('stretch_x', 'Stretch x (a):', default_stretched_dyn.stretch_x, [0.1 10.0], false, 'Positive x-stretch coefficient'), ...
    make_dyn_field('stretch_y', 'Stretch y (b):', default_stretched_dyn.stretch_y, [0.1 10.0], false, 'Positive y-stretch coefficient') ...
    ], ...
    make_shared_flags(true, true, false, false, true), ...
    'stretched_gaussian');

    make_ic_entry( ...
    'vortex_blob_gaussian', 'Vortex Blob', ...
    '\omega(r)=\frac{\Gamma}{2\pi R^2}\exp\left(-\frac{r^2}{2R^2}\right)', ...
    {'where:', '\Gamma sets circulation strength', 'R>0 sets core radius'}, ...
    [ ...
    make_dyn_field('circulation', 'Circulation (Gamma):', 1.0, [-100 100], false, 'Signed circulation'), ...
    make_dyn_field('radius', 'Radius (R):', 0.35, [1e-4 100], false, 'Gaussian core radius') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'vortex_blob_gaussian');

    make_ic_entry( ...
    'vortex_pair', 'Vortex Pair', ...
    '\omega=\omega_1+\omega_2,\;\Gamma_2=-|\Gamma_1|', ...
    {'where:', '\Gamma_1 sets pair strength', 'separation sets orbit distance', 'core radius sets compactness'}, ...
    [ ...
    make_dyn_field('gamma1', 'Gamma1 amplitude:', 1.0, [-100 100], false, 'Primary circulation'), ...
    make_dyn_field('separation', 'Separation:', 2.0, [1e-4 100], false, 'Center-to-center separation'), ...
    make_dyn_field('core_radius', 'Core radius:', 0.4, [1e-4 100], false, 'Radius of each vortex core') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'vortex_pair');

    make_ic_entry( ...
    'multi_vortex', 'Multi-Vortex', ...
    '\omega(x,y)=\sum_{i=1}^{N}\frac{\Gamma}{2\pi R^2}\exp\left(-\frac{r_i^2}{2R^2}\right)', ...
    {'where:', 'N is vortex count (>=1)', 'pattern controls center distribution', '\Gamma and R apply per vortex'}, ...
    [ ...
    make_dyn_field('gamma', 'Gamma (per vortex):', 1.0, [-100 100], false, 'Per-vortex circulation'), ...
    make_dyn_field('core_radius', 'Core radius:', 0.3, [1e-4 100], false, 'Per-vortex core radius') ...
    ], ...
    make_shared_flags(true, true, true, true, false), ...
    'multi_vortex');

    make_ic_entry( ...
    'lamb_oseen', 'Lamb-Oseen', ...
    '\omega(r)=\frac{\Gamma}{4\pi\nu t_0}\exp\left(-\frac{r^2}{4\nu t_0}\right)', ...
    {'where:', '\Gamma is circulation', '\nu>0 is viscosity', 't_0>0 broadens the core'}, ...
    [ ...
    make_dyn_field('circulation', 'Circulation (Gamma):', 1.0, [-100 100], false, 'Signed circulation'), ...
    make_dyn_field('virtual_time', 'Virtual time (t0):', 100.0, [1e-6 1e6], false, 'Equivalent diffusion time'), ...
    make_dyn_field('nu', 'Viscosity (nu):', 1e-3, [1e-10 10], false, 'Kinematic viscosity') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'lamb_oseen');

    make_ic_entry( ...
    'rankine', 'Rankine', ...
    '\omega(r)=\begin{cases}\omega_0,&r\le r_c\\0,&r>r_c\end{cases}', ...
    {'where:', '\omega_0 is core vorticity', 'r_c is cutoff radius'}, ...
    [ ...
    make_dyn_field('core_vorticity', 'Core vorticity:', 1.0, [-100 100], false, 'Plateau vorticity inside core'), ...
    make_dyn_field('core_radius', 'Core radius:', 1.0, [1e-4 100], false, 'Cutoff radius') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'rankine');

    make_ic_entry( ...
    'lamb_dipole', 'Lamb Dipole', ...
    '\omega=\omega_{\mathrm{dipole}}(r,\theta;U,a)', ...
    {'where:', 'U sets translation speed', 'a sets dipole radius'}, ...
    [ ...
    make_dyn_field('translation_speed', 'Translation speed (U):', 0.5, [-100 100], false, 'Dipole propagation speed'), ...
    make_dyn_field('dipole_radius', 'Dipole radius (a):', 1.0, [1e-4 100], false, 'Dipole radius') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'lamb_dipole');

    make_ic_entry( ...
    'taylor_green', 'Taylor-Green', ...
    '\omega(x,y)=G(k_x+k_y)\sin(k_x(x-x_0))\sin(k_y(y-y_0))', ...
    {'where:', 'm is a positive integer domain mode count', 'k_x=2\pi m/L_x and k_y=2\pi m/L_y', 'x_0,y_0 apply periodic phase shifts', 'Scale multiplies G without changing the spatial mode'}, ...
    [ ...
    make_dyn_field('wavenumber', 'Mode Count (m):', default_taylor_green_mode_count(), [1 100], true, 'Positive integer mode count across the active domain'), ...
    make_dyn_field('strength', 'Velocity Scale (G):', default_taylor_green_strength(), [-100 100], false, 'Taylor-Green velocity amplitude') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'taylor_green');

    make_ic_entry( ...
    'random_turbulence', 'Random Turbulence', ...
    '\omega(x,y)=\sum_k A_k\sin(k\cdot x+\phi_k),\;A_k\propto|k|^{-\alpha}', ...
    {'where:', '\alpha controls high-k decay', 'E_0 sets energy scale', 'seed fixes random phase realization'}, ...
    [ ...
    make_dyn_field('spectrum_exponent', 'Spectrum exponent (alpha):', 5/3, [0.1 10], false, 'Spectral decay exponent'), ...
    make_dyn_field('energy_level', 'Energy level (E0):', 1.0, [1e-8 1e6], false, 'Total energy scale'), ...
    make_dyn_field('seed', 'Seed:', 0.0, [0 1e9], true, 'Random seed') ...
    ], ...
    make_shared_flags(false, true, false, false, false), ...
    'random_turbulence');

    make_ic_entry( ...
    'elliptical_vortex', 'Elliptical Vortex', ...
    '\omega=w_0\exp\left(-\frac{x_r^2}{2\sigma_x^2}-\frac{y_r^2}{2\sigma_y^2}\right)', ...
    {'where:', 'w_0 sets peak vorticity', '\sigma_x,\sigma_y set anisotropic spread', '\theta rotates the ellipse'}, ...
    [ ...
    make_dyn_field('peak_vorticity', 'Peak vorticity:', default_elliptic_dyn.peak_vorticity, [-100 100], false, 'Maximum vortex intensity'), ...
    make_dyn_field('sigma_x', 'Sigma x:', default_elliptic_dyn.sigma_x, [1e-6 100], false, 'Spread along local x-axis'), ...
    make_dyn_field('sigma_y', 'Sigma y:', default_elliptic_dyn.sigma_y, [1e-6 100], false, 'Spread along local y-axis'), ...
    make_dyn_field('rotation_theta', 'Rotation theta (rad):', default_elliptic_dyn.rotation_theta, [-2*pi 2*pi], false, 'Ellipse rotation angle') ...
    ], ...
    make_shared_flags(true, true, false, false, false), ...
    'elliptical_vortex')
    ];
end

function scenarios = create_ic_scenario_catalog(reference_presets)
% Scenario presets with optional forced IC type and shared-value overrides.
if nargin < 1 || ~isstruct(reference_presets)
    reference_presets = create_reference_gaussian_preset_defaults(struct());
end
stretched_ref = pick_struct_block(reference_presets, {'stretched_gaussian'}, struct());
elliptic_ref = pick_struct_block(reference_presets, {'elliptical_vortex'}, struct());
scenarios = [
    make_ic_scenario('Manual', '', struct(), struct(), false, ...
    'User-driven IC editing with all controls available.', false, 'uniform_positive');
    make_ic_scenario('Single Vortex', '', ...
    struct('arrangement', 'single', 'count', 1), struct(), false, ...
    'Single localized vortex preset using the active IC family.', false, 'uniform_positive');
    make_ic_scenario( ...
    pick_struct_string(stretched_ref, {'scenario_name'}, 'Reference Spiral - Stretched Gaussian'), ...
    'stretched_gaussian', ...
    pick_struct_block(stretched_ref, {'shared_overrides'}, struct()), ...
    pick_struct_block(stretched_ref, {'dynamic_overrides'}, struct()), true, ...
    'GIF-calibrated stretched Gaussian preset referenced to VORTIC~4.GIF.', true, 'uniform_positive', ...
    struct( ...
        'preset_id', pick_struct_string(stretched_ref, {'preset_id'}, 'reference_spiral_stretched_gaussian'), ...
        'reference_asset', pick_struct_string(stretched_ref, {'reference_asset'}, 'VORTIC~4.GIF'), ...
        'runtime_overrides', pick_struct_block(stretched_ref, {'runtime_overrides'}, struct())));
    make_ic_scenario( ...
    pick_struct_string(elliptic_ref, {'scenario_name'}, 'Reference Spiral - Elliptical Vortex'), ...
    'elliptical_vortex', ...
    pick_struct_block(elliptic_ref, {'shared_overrides'}, struct()), ...
    pick_struct_block(elliptic_ref, {'dynamic_overrides'}, struct()), true, ...
    'GIF-calibrated elliptical-vortex preset referenced to VORTIC~4.GIF.', true, 'uniform_positive', ...
    struct( ...
        'preset_id', pick_struct_string(elliptic_ref, {'preset_id'}, 'reference_spiral_elliptical_vortex'), ...
        'reference_asset', pick_struct_string(elliptic_ref, {'reference_asset'}, 'VORTIC~4.GIF'), ...
        'runtime_overrides', pick_struct_block(elliptic_ref, {'runtime_overrides'}, struct())));
    make_ic_scenario('Opposing Pair', '', ...
    struct('arrangement', 'circular', 'count', 2), struct(), false, ...
    'Counter-rotating pair built from the currently selected localized IC.', true, 'alternating_opposed');
    make_ic_scenario('Ring Train', '', ...
    struct('arrangement', 'circular', 'count', 6), struct(), false, ...
    'Ring-distributed vortices built from the currently selected localized IC.', false, 'uniform_positive');
    make_ic_scenario('Random Pack', '', ...
    struct('arrangement', 'random', 'count', 8), struct(), false, ...
    'Randomly scattered localized vortices built from the currently selected localized IC.', false, 'uniform_positive');
    ];
end

function catalog = create_bathymetry_scenario_catalog_2d()
% Canonical 2D bathymetry scenarios used by FD/Spectral workflows.
catalog = [
    make_bathymetry_scenario('flat_2d', 'Flat', ...
    'y_b(x)=y_0', ...
    'IRL analog: open basin with nearly flat lower boundary', '2d', ...
    false, false, {}, ...
    make_bathymetry_shared_flags(false, false, false, false), ...
    struct([]), ...
    'Flat bathymetry has no additional designer controls.', ...
    struct());
    make_bathymetry_scenario('linear_elevation_2d', 'Linear Elevation', ...
    'y_b(x)=y_0+m(x-x_{min})', ...
    'IRL analog: gently rising seabed plane', '2d', ...
    true, false, {}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    struct([]), ...
    '', ...
    struct('bed_slope', 0.03));
    make_bathymetry_scenario('wave_profile_2d', 'Wave Profile', ...
    'y_b(x)=y_0+A[1-\cos(2\pi x/L_x)]/2', ...
    'IRL analog: long undulating seabed profile', '2d', ...
    true, false, {'wavebed_2d'}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    [ ...
    make_dyn_field('wave_height_scale', 'Wave Height Scale:', 1.0, [0.05 4.0], false, 'Scales the undulation height relative to the shared bed slope'), ...
    make_dyn_field('wave_cycles', 'Wave Cycles:', 1.0, [0.25 6.0], false, 'Number of profile oscillations across the x-domain') ...
    ], ...
    '', ...
    struct('bed_slope', 0.03));
    make_bathymetry_scenario('custom_points_2d', 'Custom Points', ...
    'y_b(x)=envelope(\mathcal{I}\{(x_i,y_i,e_i)\})', ...
    'IRL analog: survey-informed custom seabed edits', '2d', ...
    true, true, {}, ...
    make_bathymetry_shared_flags(false, false, false, true), ...
    struct([]), ...
    'Use the point editor to sculpt the profile; interpolation resolution controls preview smoothness.', ...
    struct('interpolation_resolution', 96));
    make_bathymetry_scenario('reef_2d', 'Reef', ...
    'y_b(x)=y_{base}(x)+A_r\exp(-((x-x_r)^2/\sigma_r^2))', ...
    'IRL analog: reef crest rising off the lower surface', '2d', ...
    true, false, {'reef_barrier_2d'}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    [ ...
    make_dyn_field('reef_crest_position', 'Reef Crest Position:', 0.74, [0.05 0.95], false, 'Normalized x-position of the reef crest'), ...
    make_dyn_field('reef_crest_width', 'Reef Crest Width:', 0.07, [0.01 0.30], false, 'Normalized Gaussian width of the reef crest'), ...
    make_dyn_field('reef_height_scale', 'Reef Height Scale:', 0.88, [0.05 4.0], false, 'Scales the reef crest rise relative to the shared relief') ...
    ], ...
    '', ...
    struct('bed_slope', 0.03));
    make_bathymetry_scenario('recess_2d', 'Recess', ...
    'y_b(x)=y_{base}(x)-A_d\exp(-((x-x_d)^2/\sigma_d^2))', ...
    'IRL analog: recessed pocket or local seabed depression', '2d', ...
    true, false, {'trench_cliff_2d'}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    [ ...
    make_dyn_field('recess_position', 'Recess Position:', 0.38, [0.05 0.95], false, 'Normalized x-position of the recess center'), ...
    make_dyn_field('recess_width', 'Recess Width:', 0.092, [0.01 0.35], false, 'Normalized Gaussian width of the recess'), ...
    make_dyn_field('recess_depth_scale', 'Recess Depth Scale:', 0.78, [0.05 4.0], false, 'Scales the recess depth relative to the shared relief') ...
    ], ...
    '', ...
    struct('bed_slope', 0.03));
    make_bathymetry_scenario('shore_runup_2d', 'Shore Runup', ...
    'y_b(x)=y_{base}(x)+A_s[1+\tanh((x-x_s)/\sigma_s)]/2', ...
    'IRL analog: nearshore run-up ramp toward the coastline', '2d', ...
    true, false, {'shelf_slope_2d'}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    [ ...
    make_dyn_field('shore_transition_position', 'Transition Position:', 0.72, [0.05 0.95], false, 'Normalized x-position where the shoreline steepens'), ...
    make_dyn_field('shore_transition_width', 'Transition Width:', 0.08, [0.01 0.35], false, 'Normalized tanh transition width'), ...
    make_dyn_field('runup_height_scale', 'Runup Height Scale:', 0.96, [0.05 4.0], false, 'Scales the shoreline rise relative to the shared relief') ...
    ], ...
    '', ...
    struct('bed_slope', 0.04));
    make_bathymetry_scenario('tsunami_runup_composite_2d', 'Composite Tsunami Run-up', ...
    'y_b(x)=y_{base}(x)+y_{reef}(x)+y_{undulate}(x)+y_{ravine}(x)+y_{shore}(x)', ...
    'IRL analog: reef + undercut + uneven bed + ravine + shore run-up composite', '2d', ...
    true, false, {'composite_runup_2d', 'tsunami_runup_composite'}, ...
    make_bathymetry_shared_flags(true, false, false, false), ...
    [ ...
    make_dyn_field('composite_reef_position', 'Reef Position:', 0.24, [0.05 0.95], false, 'Normalized x-position of the offshore reef crest'), ...
    make_dyn_field('composite_reef_width', 'Reef Width:', 0.05, [0.01 0.25], false, 'Normalized width of the reef crest'), ...
    make_dyn_field('composite_reef_scale', 'Reef Scale:', 0.75, [0.05 4.0], false, 'Scales reef elevation relative to the shared relief'), ...
    make_dyn_field('composite_ravine_position', 'Ravine Position:', 0.58, [0.05 0.95], false, 'Normalized x-position of the ravine center'), ...
    make_dyn_field('composite_ravine_width', 'Ravine Width:', 0.06, [0.01 0.30], false, 'Normalized width of the ravine depression'), ...
    make_dyn_field('composite_ravine_scale', 'Ravine Scale:', 1.05, [0.05 4.0], false, 'Scales ravine depth relative to the shared relief'), ...
    make_dyn_field('composite_undercut_position', 'Undercut Position:', 0.72, [0.05 0.98], false, 'Normalized x-position of the undercut transition'), ...
    make_dyn_field('composite_undercut_width', 'Undercut Width:', 0.025, [0.005 0.20], false, 'Normalized width of the undercut transition'), ...
    make_dyn_field('composite_undercut_scale', 'Undercut Scale:', 0.52, [0.05 4.0], false, 'Scales the local undercut shoulder'), ...
    make_dyn_field('composite_wave_cycles', 'Uneven Bed Cycles:', 3.0, [0.5 8.0], false, 'Number of uneven-bed oscillations across the shelf-to-shore corridor'), ...
    make_dyn_field('composite_wave_scale', 'Uneven Bed Scale:', 0.18, [0.01 2.0], false, 'Scales the short-wave uneven relief component'), ...
    make_dyn_field('composite_shore_position', 'Shore Position:', 0.82, [0.05 0.98], false, 'Normalized x-position of the shoreline steepening'), ...
    make_dyn_field('composite_shore_width', 'Shore Width:', 0.06, [0.01 0.30], false, 'Normalized width of the shoreline ramp'), ...
    make_dyn_field('composite_shore_scale', 'Shore Scale:', 0.95, [0.05 4.0], false, 'Scales the shoreline rise relative to the shared relief') ...
    ], ...
    '', ...
    struct('bed_slope', 0.035));
    make_bathymetry_scenario('tohoku_profile_2d', 'Tohoku Profile', ...
    'y_b(x)=\mathcal{S}\{p_{\mathrm{Tohoku}}(\xi)\}', ...
    'IRL analog: extracted Tohoku shelf-slope-trench transect based on ETOPO-style profile handling', '2d', ...
    true, false, {'tohoku_profile', 'tohoku_2d'}, ...
    make_bathymetry_shared_flags(false, false, false, false), ...
    [ ...
    make_dyn_field('tohoku_smoothing_strength', 'Smoothing Strength:', 1.5, [0.0 8.0], false, 'Moving-average smoothing strength applied to the extracted profile'), ...
    make_dyn_field('tohoku_depth_scale', 'Depth Scale:', 1.0, [0.25 4.0], false, 'Scales the relief depth of the extracted Tohoku profile'), ...
    make_dyn_field('tohoku_depth_offset', 'Depth Offset:', 0.0, [-0.35 0.35], false, 'Adds a normalized vertical offset before clamping to the current domain'), ...
    make_dyn_field('tohoku_horizontal_stretch', 'Horizontal Stretch:', 1.0, [0.5 2.5], false, 'Stretches or compresses the extracted transect along x before resampling'), ...
    make_dyn_field('tohoku_crop_center', 'Crop Center:', 0.50, [0.05 0.95], false, 'Normalized center of the extracted transect window'), ...
    make_dyn_field('tohoku_crop_width', 'Crop Width:', 1.0, [0.2 1.0], false, 'Normalized width of the extracted transect window retained before resampling') ...
    ], ...
    '', ...
    struct())
    ];
end

function catalog = create_bathymetry_scenario_catalog_3d()
% Canonical 3D bathymetry scenarios used by FV workflows.
catalog = [
    make_bathymetry_scenario('flat_3d', 'Flat Plane', ...
    'z_b(x,y)=z_0', ...
    'IRL analog: basin floor with low relief', '3d', ...
    false, false, {}, ...
    make_bathymetry_shared_flags(false, true, false, false), ...
    struct([]), ...
    '', ...
    struct('depth_offset', 1000.0));
    make_bathymetry_scenario('wavebed_3d', 'Wave Bed', ...
    'z_b(x,y)=z_0+A[\sin(2\pi x/L_x)+\sin(2\pi y/L_y)]', ...
    'IRL analog: intersecting seabed sandwave systems', '3d', ...
    true, false, {}, ...
    make_bathymetry_shared_flags(false, true, true, false), ...
    [ ...
    make_dyn_field('x_wave_count', 'x Wave Count:', 1.0, [1 8], true, 'Number of sinusoidal wave cycles across the x-domain'), ...
    make_dyn_field('y_wave_count', 'y Wave Count:', 1.0, [1 8], true, 'Number of sinusoidal wave cycles across the y-domain') ...
    ], ...
    '', ...
    struct('depth_offset', 1000.0, 'relief_amplitude', 180.0));
    make_bathymetry_scenario('seamount_basin_3d', 'Seamount Basin', ...
    'z_b(x,y)=z_{basin}(x,y)+A_m\exp(-r^2/\sigma_m^2)', ...
    'IRL analog: volcanic seamount rising from deep basin', '3d', ...
    true, false, {}, ...
    make_bathymetry_shared_flags(true, true, true, false), ...
    [ ...
    make_dyn_field('seamount_position_x', 'Seamount Position x:', 0.50, [0.05 0.95], false, 'Normalized x-position of the seamount center'), ...
    make_dyn_field('seamount_position_y', 'Seamount Position y:', 0.50, [0.05 0.95], false, 'Normalized y-position of the seamount center'), ...
    make_dyn_field('seamount_width', 'Seamount Width:', 0.18, [0.03 0.45], false, 'Normalized Gaussian width of the seamount'), ...
    make_dyn_field('seamount_height_scale', 'Seamount Height Scale:', 1.15, [0.05 4.0], false, 'Scales the seamount rise relative to the shared relief amplitude') ...
    ], ...
    '', ...
    struct('bed_slope', 0.03, 'depth_offset', 1000.0));
    make_bathymetry_scenario('canyon_undercut_3d', 'Canyon + Undercut', ...
    'z_b(x,y)=z_{shelf}(x)-A_c\exp(-(x-x_c)^2/\sigma_x^2-(y-y_c)^2/\sigma_y^2)+\tanh-undercut', ...
    'IRL analog: submarine canyon with sharp shelf undercut', '3d', ...
    true, false, {}, ...
    make_bathymetry_shared_flags(true, true, true, false), ...
    [ ...
    make_dyn_field('canyon_position_x', 'Canyon Position x:', 0.48, [0.05 0.95], false, 'Normalized x-position of the canyon center'), ...
    make_dyn_field('canyon_position_y', 'Canyon Position y:', 0.52, [0.05 0.95], false, 'Normalized y-position of the canyon center'), ...
    make_dyn_field('canyon_width_x', 'Canyon Width x:', 0.11, [0.02 0.35], false, 'Normalized canyon width along x'), ...
    make_dyn_field('canyon_width_y', 'Canyon Width y:', 0.18, [0.02 0.40], false, 'Normalized canyon width along y'), ...
    make_dyn_field('canyon_depth_scale', 'Canyon Depth Scale:', 1.20, [0.05 4.0], false, 'Scales the canyon depth relative to the shared relief amplitude'), ...
    make_dyn_field('undercut_position', 'Undercut Position:', 0.82, [0.05 0.98], false, 'Normalized x-position of the shelf undercut'), ...
    make_dyn_field('undercut_width', 'Undercut Width:', 0.025, [0.005 0.20], false, 'Normalized tanh width of the undercut transition'), ...
    make_dyn_field('undercut_height_scale', 'Undercut Height Scale:', 0.70, [0.05 4.0], false, 'Scales the undercut rise relative to the shared relief amplitude') ...
    ], ...
    '', ...
    struct('bed_slope', 0.035, 'depth_offset', 1000.0));
    make_bathymetry_scenario('reef_lagoon_3d', 'Reef Lagoon', ...
    'z_b(x,y)=z_{shelf}(x,y)+ring reef-lagoon profile', ...
    'IRL analog: fringing reef ring around a lagoon interior', '3d', ...
    true, false, {}, ...
    make_bathymetry_shared_flags(true, true, true, false), ...
    [ ...
    make_dyn_field('reef_radius', 'Reef Radius:', 0.62, [0.10 0.95], false, 'Normalized reef-ring radius'), ...
    make_dyn_field('reef_ring_width', 'Reef Ring Width:', 0.10, [0.01 0.30], false, 'Normalized reef-ring thickness'), ...
    make_dyn_field('reef_height_scale', 'Reef Height Scale:', 1.05, [0.05 4.0], false, 'Scales the reef-ring rise relative to the shared relief amplitude'), ...
    make_dyn_field('lagoon_radius', 'Lagoon Radius:', 0.42, [0.05 0.90], false, 'Normalized lagoon-core radius'), ...
    make_dyn_field('lagoon_depth_scale', 'Lagoon Depth Scale:', 0.75, [0.05 4.0], false, 'Scales the lagoon depth relative to the shared relief amplitude') ...
    ], ...
    '', ...
    struct('bed_slope', 0.03, 'depth_offset', 1000.0))
    ];
end

function scenarios = create_simulation_scenario_catalog()
% Full-stack simulation scenario presets (method/mode/mesh/BC/IC/bathy).
scenarios = [
    make_simulation_scenario('Manual', ...
    'User-controlled setup. No automatic override bundle applied.', ...
    struct());
    make_simulation_scenario('Coastal Shelf Runup', ...
    'Nearshore shelf-slope vorticity setup over shaped bathymetry.', ...
    struct( ...
    'method', 'finite_difference', ...
    'mode', 'evolution', ...
    'Nx', 256, ...
    'Ny', 192, ...
    'Lx', 20.0, ...
    'Ly', 10.0, ...
    'dt', 0.005, ...
    'Tfinal', 6.0, ...
    'bc_case', 'enclosed_cavity', ...
    'ic_type', 'elliptical_vortex', ...
    'ic_scenario', 'Manual', ...
    'bathymetry_scenario', 'shore_runup_2d', ...
    'bathymetry_bed_slope', 0.04));
    make_simulation_scenario('Reef Impact Test', ...
    'Barrier-reef interaction setup for localized vorticity amplification.', ...
    struct( ...
    'method', 'finite_difference', ...
    'mode', 'evolution', ...
    'Nx', 256, ...
    'Ny', 192, ...
    'Lx', 18.0, ...
    'Ly', 12.0, ...
    'dt', 0.005, ...
    'Tfinal', 6.0, ...
    'bc_case', 'enclosed_cavity', ...
    'ic_type', 'vortex_blob_gaussian', ...
    'ic_scenario', 'Manual', ...
    'bathymetry_scenario', 'reef_2d', ...
    'bathymetry_bed_slope', 0.03));
    make_simulation_scenario('Canyon Focusing Test', ...
    'Canyon/undercut focusing setup using FV vorticity evolution.', ...
    struct( ...
    'method', 'finite_volume', ...
    'mode', 'evolution', ...
    'Nx', 192, ...
    'Ny', 192, ...
    'Lx', 24.0, ...
    'Ly', 18.0, ...
    'dt', 0.004, ...
    'Tfinal', 5.0, ...
    'bc_case', 'enclosed_cavity', ...
    'ic_type', 'multi_vortex', ...
    'ic_scenario', 'Ring Train', ...
    'bathymetry_scenario', 'canyon_undercut_3d', ...
    'bathymetry_bed_slope', 0.035));
    make_simulation_scenario('SWE Coastal Shelf Runup', ...
    'Classical SWE runup over a nearshore shelf with open-coast boundaries.', ...
    struct( ...
    'method', 'shallow_water', ...
    'mode', 'evolution', ...
    'Nx', 240, ...
    'Ny', 120, ...
    'Lx', 20.0, ...
    'Ly', 10.0, ...
    'dt', 0.01, ...
    'Tfinal', 8.0, ...
    'bc_case', 'user_defined', ...
    'bc_top', 'No-slip (Dirichlet)', ...
    'bc_bottom', 'No-slip (Dirichlet)', ...
    'bc_left', 'Open (Absorbing)', ...
    'bc_right', 'Open (Absorbing)', ...
    'bathymetry_scenario', 'shore_runup_2d', ...
    'bathymetry_bed_slope', 0.05, ...
    'time_integrator', 'RK3', ...
    'method_config', struct('swe2d', struct( ...
    'initial_condition', 'solitary_eta', ...
    'surface_amplitude', 0.09, ...
    'surface_sigma_x', 0.85, ...
    'surface_sigma_y', 0.60, ...
    'surface_center_x', -5.5, ...
    'surface_center_y', 0.0, ...
    'base_depth', 1.0, ...
    'bed_relief_fraction', 1.20, ...
    'cfl', 0.45))));
    make_simulation_scenario('SWE Reef Impact', ...
    'Classical SWE pulse interacting with a reef crest and lagoon-like bed relief.', ...
    struct( ...
    'method', 'shallow_water', ...
    'mode', 'evolution', ...
    'Nx', 220, ...
    'Ny', 140, ...
    'Lx', 18.0, ...
    'Ly', 12.0, ...
    'dt', 0.01, ...
    'Tfinal', 7.0, ...
    'bc_case', 'user_defined', ...
    'bc_top', 'No-slip (Dirichlet)', ...
    'bc_bottom', 'No-slip (Dirichlet)', ...
    'bc_left', 'Open (Absorbing)', ...
    'bc_right', 'Open (Absorbing)', ...
    'bathymetry_scenario', 'reef_2d', ...
    'bathymetry_bed_slope', 0.03, ...
    'time_integrator', 'RK3', ...
    'method_config', struct('swe2d', struct( ...
    'initial_condition', 'solitary_eta', ...
    'surface_amplitude', 0.07, ...
    'surface_sigma_x', 0.75, ...
    'surface_sigma_y', 0.90, ...
    'surface_center_x', -4.8, ...
    'surface_center_y', 0.0, ...
    'base_depth', 1.0, ...
    'bed_relief_fraction', 1.10, ...
    'cfl', 0.45))));
    make_simulation_scenario('SWE Shelf Momentum Pulse', ...
    'Classical SWE momentum-pulse benchmark for coastal shelf focusing.', ...
    struct( ...
    'method', 'shallow_water', ...
    'mode', 'evolution', ...
    'Nx', 200, ...
    'Ny', 120, ...
    'Lx', 16.0, ...
    'Ly', 10.0, ...
    'dt', 0.01, ...
    'Tfinal', 6.0, ...
    'bc_case', 'user_defined', ...
    'bc_top', 'No-slip (Dirichlet)', ...
    'bc_bottom', 'No-slip (Dirichlet)', ...
    'bc_left', 'Open (Absorbing)', ...
    'bc_right', 'Open (Absorbing)', ...
    'bathymetry_scenario', 'linear_elevation_2d', ...
    'bathymetry_bed_slope', 0.035, ...
    'time_integrator', 'RK3', ...
    'method_config', struct('swe2d', struct( ...
    'initial_condition', 'momentum_gaussian', ...
    'momentum_amplitude_x', 0.45, ...
    'momentum_amplitude_y', 0.0, ...
    'surface_sigma_x', 0.80, ...
    'surface_sigma_y', 0.70, ...
    'surface_center_x', -3.8, ...
    'surface_center_y', 0.0, ...
    'base_depth', 1.0, ...
    'bed_relief_fraction', 1.05, ...
    'cfl', 0.45))))
    ];
end

function catalog = create_ic_arrangement_catalog()
% Canonical arrangement tokens used by the IC editor.
catalog = [
    make_arrangement_entry('single', 'Single', ...
    'Use one localized vortex placement or one effective center.');
    make_arrangement_entry('circular', 'Circular', ...
    'Distribute localized vortices on a ring around the center.');
    make_arrangement_entry('grid', 'Grid', ...
    'Distribute localized vortices on a Cartesian lattice.');
    make_arrangement_entry('random', 'Random', ...
    'Scatter localized vortices within the available domain footprint.')
    ];
end

function defaults = create_ic_multi_vortex_defaults()
% Canonical defaults for the multi-vortex popup/editor.
defaults = struct( ...
    'allow_mixed_types', true, ...
    'blocked_domain_filling_types', {{'taylor_green', 'random_turbulence'}}, ...
    'table_columns', {{'enabled', 'ic_type', 'x0', 'y0', 'scale', 'amplitude', 'charge'}});
end

function rows = create_default_multi_vortex_rows()
% Default multi-vortex schema-v2 row set.
rows = repmat(struct( ...
    'row_id', 1, ...
    'enabled', true, ...
    'ic_type', 'elliptical_vortex', ...
    'center_x', 0.0, ...
    'center_y', 0.0, ...
    'scale', 1.0, ...
    'amplitude', 1.0, ...
    'charge', 1.0, ...
    'dynamic_values', create_default_elliptical_dynamic_values()), 1, 1);
end

function cfg = create_phase1_ic_study_config(base_params)
reference_presets = pick_struct_block(base_params, {'reference_calibration_presets'}, struct());
cfg = struct();
cfg.enabled = true;
cfg.include_arrangement_cases = false;
cfg.active_case_ids = {'taylor_green'};
cfg.baseline_ic_type = 'elliptical_vortex';
cfg.selected_case_id = 'baseline_elliptic_single';
cfg.selected_group = 'Elliptical Vortex';
cfg.selected_preset = pick_struct_string(pick_struct_block(reference_presets, {'elliptical_vortex'}, struct()), {'label'}, 'Reference Spiral - Elliptical Vortex');
cfg.baseline_label = cfg.selected_preset;
cfg.reference_evolution = create_phase1_reference_evolution_config();
cfg.groups = [ ...
    struct( ...
        'id', 'stretched_gaussian', ...
        'label', 'Stretched Gaussian', ...
        'presets', {{'Stretched Gaussian', pick_struct_string(pick_struct_block(reference_presets, {'stretched_gaussian'}, struct()), {'label'}, 'Reference Spiral - Stretched Gaussian')}}); ...
    struct( ...
        'id', 'elliptical_vortex', ...
        'label', 'Elliptical Vortex', ...
        'presets', {{pick_struct_string(pick_struct_block(reference_presets, {'elliptical_vortex'}, struct()), {'label'}, 'Reference Spiral - Elliptical Vortex'), 'Polar Opposites', 'Random Pack', 'Ring Train'}}); ...
    struct( ...
        'id', 'taylor_green', ...
        'label', 'Taylor-Green', ...
        'presets', {{'Taylor-Green'}}) ...
    ];
cfg.catalog = create_phase1_ic_study_catalog(base_params);
cfg.chart_case_labels = {cfg.baseline_label, cfg.catalog.label};
end

function ref = create_phase1_reference_evolution_config()
repo_root = resolve_default_parameters_repo_root();
asset_rel_path = 'VORTIC~4.GIF';
asset_abs_path = fullfile(repo_root, asset_rel_path);
ref = struct( ...
    'enabled', true, ...
    'publish_in_phase_workflow', false, ...
    'asset_name', 'VORTIC~4.GIF', ...
    'asset_rel_path', asset_rel_path, ...
    'asset_path', asset_abs_path, ...
    'asset_exists', exist(asset_abs_path, 'file') == 2, ...
    'expected_frame_count', 9, ...
    'comparison_grid_rows', 3, ...
    'comparison_grid_cols', 3, ...
    'calibration_grid_n', 128, ...
    'calibration_tfinal_s', 8.0, ...
    'calibration_plot_snapshot_count', 9, ...
    'calibration_method_scope', {{'FD', 'Spectral'}}, ...
    'calibration_metric_fields', {{ ...
        'grayscale_rmse', ...
        'contour_overlap_loss', ...
        'core_principal_axis_angle_error_rad', ...
        'spiral_arm_angle_error_rad', ...
        'composite_gif_match_score'}}, ...
    'preserve_simulation_frame_count', true, ...
    'use_for_phase1_comparison_grid', false, ...
    'target_ic_types', {{'stretched_gaussian', 'elliptical_vortex'}});
end

function dyn = create_default_stretched_gaussian_dynamic_values()
dyn = struct('stretch_x', 2.15, 'stretch_y', 0.18);
end

function dyn = create_default_elliptical_dynamic_values()
dyn = make_reference_elliptical_shape_from_stretched(create_default_stretched_gaussian_dynamic_values(), 1.0, 0.0);
end

function value = default_calibrated_stretched_scale()
value = 2.75;
end

function value = default_calibrated_stretched_nu()
value = 1.0e-7;
end

function value = default_taylor_green_mode_count()
value = 2.0;
end

function value = default_taylor_green_strength()
value = 2.0;
end

function value = default_taylor_green_nu()
value = 2.0e-2;
end

function runtime = create_default_taylor_green_runtime_overrides(base_params)
if nargin < 1 || ~isstruct(base_params)
    base_params = struct();
end
mode_count = default_taylor_green_mode_count();
strength = default_taylor_green_strength();
center_x = pick_struct_numeric(base_params, {'ic_center_x'}, 0.0);
center_y = pick_struct_numeric(base_params, {'ic_center_y'}, 0.0);
runtime = struct( ...
    'ic_type', 'taylor_green', ...
    'ic_scenario', 'Taylor-Green', ...
    'ic_coeff', [mode_count, strength, 0.0, 0.0, center_x, center_y], ...
    'ic_dynamic_values', struct('wavenumber', mode_count, 'strength', strength), ...
    'ic_center_x', center_x, ...
    'ic_center_y', center_y, ...
    'ic_scale', 1.0, ...
    'ic_amplitude', 1.0, ...
    'ic_count', 1, ...
    'ic_pattern', 'single', ...
    'ic_arrangement', 'single', ...
    'ic_multi_vortex_experimental', false, ...
    'ic_multi_vortex_rows', struct([]), ...
    'nu', default_taylor_green_nu());
end

function params = apply_default_ic_runtime_snapshot(params, snapshot)
if nargin < 1 || ~isstruct(params) || nargin < 2 || ~isstruct(snapshot)
    return;
end

text_fields = {'ic_type', 'ic_scenario', 'ic_pattern', 'ic_arrangement'};
for i = 1:numel(text_fields)
    key = text_fields{i};
    if isfield(snapshot, key) && ~isempty(snapshot.(key))
        params.(key) = char(string(snapshot.(key)));
    end
end

numeric_fields = {'ic_center_x', 'ic_center_y', 'ic_scale', 'ic_amplitude', ...
    'ic_coeff1', 'ic_coeff2', 'ic_coeff3', 'ic_coeff4', 'nu'};
for i = 1:numel(numeric_fields)
    key = numeric_fields{i};
    if isfield(snapshot, key) && isnumeric(snapshot.(key)) && isscalar(snapshot.(key)) && ...
            isfinite(snapshot.(key))
        params.(key) = double(snapshot.(key));
    end
end

if isfield(snapshot, 'ic_coeff') && isnumeric(snapshot.ic_coeff)
    params.ic_coeff = double(snapshot.ic_coeff(:).');
end
if isfield(snapshot, 'ic_dynamic_values') && isstruct(snapshot.ic_dynamic_values)
    params.ic_dynamic_values = snapshot.ic_dynamic_values;
end
if isfield(snapshot, 'ic_count') && isnumeric(snapshot.ic_count) && isscalar(snapshot.ic_count) && ...
        isfinite(snapshot.ic_count)
    params.ic_count = max(1, round(double(snapshot.ic_count)));
end
if isfield(snapshot, 'ic_multi_vortex_rows')
    params.ic_multi_vortex_rows = snapshot.ic_multi_vortex_rows;
end
if isfield(snapshot, 'ic_multi_vortex_experimental')
    params.ic_multi_vortex_experimental = logical(snapshot.ic_multi_vortex_experimental);
end
end

function presets = create_reference_gaussian_preset_defaults(base_params)
baseline_center_x = pick_struct_numeric(base_params, {'ic_center_x'}, 0.0);
baseline_center_y = pick_struct_numeric(base_params, {'ic_center_y'}, 0.0);
baseline_scale = pick_struct_numeric(base_params, {'ic_scale'}, default_calibrated_stretched_scale());
baseline_amplitude = pick_struct_numeric(base_params, {'ic_amplitude'}, 1.0);
baseline_nu = pick_struct_numeric(base_params, {'nu'}, default_calibrated_stretched_nu());

stretched_scale = pick_struct_numeric(base_params, {'ic_scale'}, default_calibrated_stretched_scale());
stretched_dyn = pick_struct_block(base_params, {'ic_dynamic_values'}, create_default_stretched_gaussian_dynamic_values());
stretched_runtime = struct( ...
    'ic_type', 'stretched_gaussian', ...
    'ic_scenario', 'Reference Spiral - Stretched Gaussian', ...
    'ic_coeff', [stretched_dyn.stretch_x, stretched_dyn.stretch_y, stretched_scale * baseline_amplitude, 0.0, baseline_center_x, baseline_center_y], ...
    'ic_dynamic_values', stretched_dyn, ...
    'ic_center_x', baseline_center_x, ...
    'ic_center_y', baseline_center_y, ...
    'ic_scale', stretched_scale, ...
    'ic_amplitude', baseline_amplitude, ...
    'ic_count', 1, ...
    'ic_pattern', 'single', ...
    'ic_arrangement', 'single', ...
    'ic_multi_vortex_experimental', false, ...
    'ic_multi_vortex_rows', struct([]), ...
    'nu', baseline_nu);

elliptic_dyn = make_reference_elliptical_shape_from_stretched(stretched_dyn, 1.0, 0.0);
elliptic_runtime = struct( ...
    'ic_type', 'elliptical_vortex', ...
    'ic_scenario', 'Reference Spiral - Elliptical Vortex', ...
    'ic_coeff', [elliptic_dyn.peak_vorticity * stretched_scale, elliptic_dyn.sigma_x, elliptic_dyn.sigma_y, elliptic_dyn.rotation_theta, baseline_center_x, baseline_center_y], ...
    'ic_dynamic_values', elliptic_dyn, ...
    'ic_center_x', baseline_center_x, ...
    'ic_center_y', baseline_center_y, ...
    'ic_scale', baseline_scale, ...
    'ic_amplitude', baseline_amplitude, ...
    'ic_count', 1, ...
    'ic_pattern', 'single', ...
    'ic_arrangement', 'single', ...
    'ic_multi_vortex_experimental', false, ...
    'ic_multi_vortex_rows', struct([]), ...
    'nu', baseline_nu);

presets = struct( ...
    'stretched_gaussian', struct( ...
        'preset_id', 'reference_spiral_stretched_gaussian', ...
        'scenario_name', 'Reference Spiral - Stretched Gaussian', ...
        'label', 'Reference Spiral - Stretched Gaussian', ...
        'group_label', 'Stretched Gaussian', ...
        'reference_asset', 'VORTIC~4.GIF', ...
        'shared_overrides', struct('arrangement', 'single', 'count', 1, 'center_x', baseline_center_x, 'center_y', baseline_center_y, 'scale', stretched_scale, 'amplitude', baseline_amplitude), ...
        'dynamic_overrides', stretched_dyn, ...
        'runtime_overrides', stretched_runtime, ...
        'nu', baseline_nu), ...
    'elliptical_vortex', struct( ...
        'preset_id', 'reference_spiral_elliptical_vortex', ...
        'scenario_name', 'Reference Spiral - Elliptical Vortex', ...
        'label', 'Reference Spiral - Elliptical Vortex', ...
        'group_label', 'Elliptical Vortex', ...
        'reference_asset', 'VORTIC~4.GIF', ...
        'shared_overrides', struct('arrangement', 'single', 'count', 1, 'center_x', baseline_center_x, 'center_y', baseline_center_y, 'scale', stretched_scale, 'amplitude', baseline_amplitude), ...
        'dynamic_overrides', elliptic_dyn, ...
        'runtime_overrides', elliptic_runtime, ...
        'nu', baseline_nu));
end

function dyn = make_reference_elliptical_shape_from_stretched(stretched_dyn, peak_vorticity, rotation_theta)
stretch_x = pick_struct_numeric(stretched_dyn, {'stretch_x'}, 2.15);
stretch_y = pick_struct_numeric(stretched_dyn, {'stretch_y'}, 0.18);
stretch_x = max(double(stretch_x), 1.0e-12);
stretch_y = max(double(stretch_y), 1.0e-12);
dyn = struct( ...
    'peak_vorticity', double(peak_vorticity), ...
    'sigma_x', 1.0 / sqrt(2.0 * stretch_x), ...
    'sigma_y', 1.0 / sqrt(2.0 * stretch_y), ...
    'rotation_theta', double(rotation_theta));
end

function repo_root = resolve_default_parameters_repo_root()
this_dir = fileparts(mfilename('fullpath'));
repo_root = fullfile(this_dir, '..', '..', '..');
repo_root = char(java.io.File(repo_root).getCanonicalPath());
end

function catalog = create_phase1_ic_study_catalog(base_params)
reference_presets = pick_struct_block(base_params, {'reference_calibration_presets'}, struct());
stretched_ref = pick_struct_block(reference_presets, {'stretched_gaussian'}, struct());
elliptic_ref = pick_struct_block(reference_presets, {'elliptical_vortex'}, struct());
stretched_scale = pick_struct_numeric(stretched_ref, {'runtime_overrides', 'ic_scale'}, default_calibrated_stretched_scale());
stretched_dyn = pick_struct_block(stretched_ref, {'dynamic_overrides'}, create_default_stretched_gaussian_dynamic_values());
elliptic_dyn = pick_struct_block(elliptic_ref, {'dynamic_overrides'}, ...
    make_reference_elliptical_shape_from_stretched(stretched_dyn, 1.0, 0.0));
baseline_center_x = pick_struct_numeric(base_params, {'ic_center_x'}, 0.0);
baseline_center_y = pick_struct_numeric(base_params, {'ic_center_y'}, 0.0);
baseline_scale = pick_struct_numeric(base_params, {'ic_scale'}, default_calibrated_stretched_scale());
baseline_amplitude = pick_struct_numeric(base_params, {'ic_amplitude'}, 1.0);
catalog = [ ...
    make_phase1_ic_study_case( ...
        'reference_spiral_stretched_gaussian', ...
        pick_struct_string(stretched_ref, {'label'}, 'Reference Spiral - Stretched Gaussian'), ...
        'Stretched Gaussian', ...
        'stretched_gaussian', ...
        pick_struct_block(stretched_ref, {'runtime_overrides'}, struct( ...
            'ic_scenario', pick_struct_string(stretched_ref, {'scenario_name'}, 'Reference Spiral - Stretched Gaussian'), ...
            'ic_coeff', [ ...
                pick_struct_numeric(stretched_dyn, {'stretch_x'}, 2.15), ...
                pick_struct_numeric(stretched_dyn, {'stretch_y'}, 0.18), ...
                stretched_scale * baseline_amplitude, 0.0, baseline_center_x, baseline_center_y], ...
            'ic_dynamic_values', stretched_dyn, ...
            'ic_center_x', baseline_center_x, ...
            'ic_center_y', baseline_center_y, ...
            'ic_scale', stretched_scale, ...
            'ic_amplitude', baseline_amplitude, ...
            'ic_count', 1, ...
            'ic_pattern', 'single', ...
            'ic_arrangement', 'single', ...
            'ic_multi_vortex_experimental', false, ...
            'ic_multi_vortex_rows', struct([]), ...
            'nu', pick_struct_numeric(stretched_ref, {'nu'}, pick_struct_numeric(base_params, {'nu'}, 1e-6))))); ...
    make_phase1_ic_study_case( ...
        'reference_spiral_elliptical_vortex', ...
        pick_struct_string(elliptic_ref, {'label'}, 'Reference Spiral - Elliptical Vortex'), ...
        'Elliptical Vortex', ...
        'elliptical_vortex', ...
        pick_struct_block(elliptic_ref, {'runtime_overrides'}, struct( ...
            'ic_scenario', pick_struct_string(elliptic_ref, {'scenario_name'}, 'Reference Spiral - Elliptical Vortex'), ...
            'ic_coeff', [ ...
                pick_struct_numeric(elliptic_dyn, {'peak_vorticity'}, 1.0) * baseline_scale, ...
                pick_struct_numeric(elliptic_dyn, {'sigma_x'}, 1.0), ...
                pick_struct_numeric(elliptic_dyn, {'sigma_y'}, 0.5), ...
                pick_struct_numeric(elliptic_dyn, {'rotation_theta'}, 0.0), ...
                baseline_center_x, baseline_center_y], ...
            'ic_dynamic_values', elliptic_dyn, ...
            'ic_center_x', baseline_center_x, ...
            'ic_center_y', baseline_center_y, ...
            'ic_scale', baseline_scale, ...
            'ic_amplitude', baseline_amplitude, ...
            'ic_count', 1, ...
            'ic_pattern', 'single', ...
            'ic_arrangement', 'single', ...
            'ic_multi_vortex_experimental', false, ...
            'ic_multi_vortex_rows', struct([]), ...
            'nu', pick_struct_numeric(elliptic_ref, {'nu'}, pick_struct_numeric(base_params, {'nu'}, 1e-6))))); ...
    make_phase1_ic_study_case( ...
        'taylor_green', 'Taylor-Green', 'Taylor-Green', ...
        'taylor_green', create_default_taylor_green_runtime_overrides(base_params)); ...
    make_phase1_ic_study_case( ...
        'polar_opposites', 'Polar Opposites', 'Elliptical Vortex', ...
        'elliptical_vortex', struct( ...
            'ic_scenario', 'Polar Opposites', ...
            'ic_coeff', [1.0, 1.0, 0.5, pi/2, baseline_center_x, baseline_center_y], ...
            'ic_dynamic_values', elliptic_dyn, ...
            'ic_center_x', baseline_center_x, ...
            'ic_center_y', baseline_center_y, ...
            'ic_scale', baseline_scale, ...
            'ic_amplitude', baseline_amplitude, ...
            'ic_count', 2, ...
            'ic_pattern', 'circular', ...
            'ic_arrangement', 'circular', ...
            'ic_multi_vortex_experimental', true, ...
            'ic_multi_vortex_rows', create_phase1_polar_opposites_rows(elliptic_dyn))); ...
    make_phase1_ic_study_case( ...
        'random_pack', 'Random Pack', 'Elliptical Vortex', ...
        'elliptical_vortex', struct( ...
            'ic_scenario', 'Random Pack', ...
            'ic_coeff', [1.0, 1.0, 0.5, pi/2, baseline_center_x, baseline_center_y], ...
            'ic_dynamic_values', elliptic_dyn, ...
            'ic_center_x', baseline_center_x, ...
            'ic_center_y', baseline_center_y, ...
            'ic_scale', baseline_scale, ...
            'ic_amplitude', baseline_amplitude, ...
            'ic_count', 8, ...
            'ic_pattern', 'random', ...
            'ic_arrangement', 'random', ...
            'ic_multi_vortex_experimental', true, ...
            'ic_multi_vortex_rows', create_phase1_random_pack_rows(elliptic_dyn))); ...
    make_phase1_ic_study_case( ...
        'ring_train', 'Ring Train', 'Elliptical Vortex', ...
        'elliptical_vortex', struct( ...
            'ic_scenario', 'Ring Train', ...
            'ic_coeff', [1.0, 1.0, 0.5, pi/2, baseline_center_x, baseline_center_y], ...
            'ic_dynamic_values', elliptic_dyn, ...
            'ic_center_x', baseline_center_x, ...
            'ic_center_y', baseline_center_y, ...
            'ic_scale', baseline_scale, ...
            'ic_amplitude', baseline_amplitude, ...
            'ic_count', 6, ...
            'ic_pattern', 'circular', ...
            'ic_arrangement', 'circular', ...
            'ic_multi_vortex_experimental', true, ...
            'ic_multi_vortex_rows', create_phase1_ring_train_rows(elliptic_dyn))) ...
    ];
end

function entry = make_phase1_ic_study_case(case_id, label, group_label, ic_type, overrides)
entry = struct( ...
    'case_id', char(string(case_id)), ...
    'label', char(string(label)), ...
    'group_label', char(string(group_label)), ...
    'ic_type', char(string(ic_type)), ...
    'runtime_overrides', overrides);
end

function rows = create_phase1_polar_opposites_rows(dynamic_values)
rows = repmat(create_phase1_ic_study_row(1, 0.0, 0.0, 1.0, 1.0, 1.0, dynamic_values), 2, 1);
rows(1) = create_phase1_ic_study_row(1, -1.75, 0.0, 1.0, 1.0, 1.0, dynamic_values);
rows(2) = create_phase1_ic_study_row(2, 1.75, 0.0, 1.0, 1.0, -1.0, dynamic_values);
end

function rows = create_phase1_random_pack_rows(dynamic_values)
centers = [ ...
    -2.8, -1.9; ...
    2.1, -2.2; ...
    -1.5, 2.0; ...
    1.8, 1.6; ...
    -3.2, 0.9; ...
    3.1, 0.4; ...
    -0.6, -0.3; ...
    0.8, 2.8];
rows = repmat(create_phase1_ic_study_row(1, 0.0, 0.0, 0.85, 1.0, 1.0, dynamic_values), size(centers, 1), 1);
for i = 1:size(centers, 1)
    rows(i) = create_phase1_ic_study_row(i, centers(i, 1), centers(i, 2), 0.85, 1.0, 1.0, dynamic_values);
end
end

function rows = create_phase1_ring_train_rows(dynamic_values)
theta = linspace(0, 2 * pi, 7);
theta(end) = [];
radius = 3.0;
rows = repmat(create_phase1_ic_study_row(1, 0.0, 0.0, 0.9, 1.0, 1.0, dynamic_values), numel(theta), 1);
for i = 1:numel(theta)
    rows(i) = create_phase1_ic_study_row( ...
        i, radius * cos(theta(i)), radius * sin(theta(i)), 0.9, 1.0, 1.0, dynamic_values);
end
end

function row = create_phase1_ic_study_row(row_id, center_x, center_y, scale, amplitude, charge, dynamic_values)
row = struct( ...
    'row_id', round(double(row_id)), ...
    'enabled', true, ...
    'ic_type', 'elliptical_vortex', ...
    'center_x', double(center_x), ...
    'center_y', double(center_y), ...
    'scale', double(scale), ...
    'amplitude', double(amplitude), ...
    'charge', double(charge), ...
    'dynamic_values', dynamic_values, ...
    'preset_tag', 'phase1_ic_study');
end

function value = pick_struct_numeric(s, field_names, fallback)
value = fallback;
if ~isstruct(s)
    return;
end
for i = 1:numel(field_names)
    key = field_names{i};
    if isfield(s, key) && isnumeric(s.(key)) && isscalar(s.(key)) && isfinite(s.(key))
        value = double(s.(key));
        return;
    end
end
end

function value = pick_struct_block(s, field_names, fallback)
value = fallback;
if ~isstruct(s)
    return;
end
for i = 1:numel(field_names)
    key = field_names{i};
    if isfield(s, key) && isstruct(s.(key))
        value = s.(key);
        return;
    end
end
end

function value = pick_struct_string(s, field_names, fallback)
value = char(string(fallback));
if ~isstruct(s)
    return;
end
for i = 1:numel(field_names)
    key = field_names{i};
    if isfield(s, key) && ~isempty(s.(key))
        value = char(string(s.(key)));
        return;
    end
end
end

function entry = make_ic_entry(ic_type, display_name, equation_tex, where_entries, dynamic_fields, shared_flags, pack_mode)
% make_ic_entry: construct a catalog entry struct describing an
% initial condition (IC) type used by the UI and runtime.
% Fields (canonical):
%   - ic_type: string identifier for the IC generator (e.g. 'stretched_gaussian')
%   - display_name: human readable name
%   - equation_tex: LaTeX expression describing the IC
%   - where_entries: structured variable guidance for the UI
%   - dynamic_fields: array of dynamic field structs created by make_dyn_field
%   - shared_flags: struct of booleans controlling which shared controls to show
%   - pack_mode: optional packing mode hint used by the UI
%//TODO: Add more explicit validation/logging here if catalog entries are malformed.
if ~isstruct(where_entries)
    where_entries = create_default_where_entries(ic_type);
end
ic_token = char(string(ic_type));
entry = struct( ...
    'ic_type', ic_token, ...
    'display_name', char(string(display_name)), ...
    'equation_tex', char(string(equation_tex)), ...
    'where_entries', where_entries, ...
    'dynamic_fields', dynamic_fields, ...
    'shared_flags', shared_flags, ...
    'pack_mode', char(string(pack_mode)), ...
    'supports_multi_vortex', ~any(strcmpi(ic_token, {'taylor_green', 'random_turbulence', 'no_initial_condition'})), ...
    'supports_mixed_popup', ~any(strcmpi(ic_token, {'taylor_green', 'random_turbulence', 'no_initial_condition'})), ...
    'arrangement_applicable', any(strcmpi(ic_token, { ...
    'stretched_gaussian', 'vortex_blob_gaussian', 'multi_vortex', ...
    'lamb_oseen', 'rankine', 'lamb_dipole', 'elliptical_vortex', 'vortex_pair'})), ...
    'preview_mode', resolve_ic_preview_mode(ic_type));
end

function field = make_dyn_field(id, label, default_value, limits, is_integer, tooltip)
% make_dyn_field: create a descriptor for a single dynamic UI field.
% Descriptor fields:
%   - id: machine id used to reference the value
%   - label: label shown in the UI
%   - default: numeric default value (stored as double)
%   - limits: numeric two-element vector [min max]
%   - is_integer: logical indicating integer-only values
%   - tooltip: help text for the field
%//TODO: Consider supporting non-numeric defaults (strings/enums) in future.
field = struct( ...
    'id', char(string(id)), ...
    'label', char(string(label)), ...
    'default', double(default_value), ...
    'limits', double(limits), ...
    'is_integer', logical(is_integer), ...
    'tooltip', char(string(tooltip)));
end

function flags = make_shared_flags(show_position, show_scale, show_count, show_pattern, show_amplitude)
% make_shared_flags: convenience constructor for UI visibility flags.
% Fields are logicals that control whether shared controls appear:
%   - show_position, show_scale, show_count, show_pattern, show_amplitude
%//TODO: Document how these interact with the IC editor; add unit tests.
flags = struct( ...
    'show_position', logical(show_position), ...
    'show_scale', logical(show_scale), ...
    'show_count', logical(show_count), ...
    'show_pattern', logical(show_pattern), ...
    'show_amplitude', logical(show_amplitude));
end

function entry = make_ic_scenario(name, forced_ic_type, shared_overrides, dynamic_overrides, lock_ic_type_dropdown, description, lock_arrangement, charge_pattern, extra_fields)
% make_ic_scenario: scenario presets for quickly configuring multiple
% initial conditions at once. Fields:
%   - scenario_name: display name for the preset
%   - forced_ic_type: if non-empty, UI should lock/force the IC type
%   - shared_overrides: struct of values that override shared parameters
%   - dynamic_overrides: struct of overrides for dynamic fields
%   - lock_ic_type_dropdown: logical, whether to lock the IC type selector
%//TODO: Add automated check that overrides only contain known keys.
if nargin < 8 || isempty(charge_pattern)
    charge_pattern = 'uniform_positive';
end
if nargin < 9 || ~isstruct(extra_fields)
    extra_fields = struct();
end
entry = struct( ...
    'scenario_name', char(string(name)), ...
    'forced_ic_type', char(string(forced_ic_type)), ...
    'shared_overrides', shared_overrides, ...
    'dynamic_overrides', dynamic_overrides, ...
    'lock_ic_type_dropdown', logical(lock_ic_type_dropdown), ...
    'description', char(string(description)), ...
    'lock_arrangement', logical(lock_arrangement), ...
    'charge_pattern', char(string(charge_pattern)), ...
    'preset_id', '', ...
    'reference_asset', '', ...
    'runtime_overrides', struct());
extra_names = fieldnames(extra_fields);
for idx = 1:numel(extra_names)
    entry.(extra_names{idx}) = extra_fields.(extra_names{idx});
end
end

function entry = make_arrangement_entry(id, display_name, description)
entry = struct( ...
    'id', char(string(id)), ...
    'display_name', char(string(display_name)), ...
    'description', char(string(description)));
end

function entry = make_bathymetry_scenario(id, display_name, equation_tex, irl_label, dimension, blocks_periodic_bc, uses_point_editor, legacy_aliases, shared_flags, dynamic_fields, empty_state_text, shared_defaults)
entry = struct( ...
    'id', char(string(id)), ...
    'display_name', char(string(display_name)), ...
    'equation_tex', char(string(equation_tex)), ...
    'irl_label', char(string(irl_label)), ...
    'dimension', lower(char(string(dimension))), ...
    'blocks_periodic_bc', logical(blocks_periodic_bc), ...
    'uses_point_editor', logical(uses_point_editor), ...
    'legacy_aliases', {cellstr(string(legacy_aliases))}, ...
    'shared_flags', shared_flags, ...
    'dynamic_fields', dynamic_fields, ...
    'empty_state_text', char(string(empty_state_text)), ...
    'shared_defaults', shared_defaults);
end

function flags = make_bathymetry_shared_flags(show_bed_slope, show_depth_offset, show_relief_amplitude, show_resolution)
flags = struct( ...
    'show_bed_slope', logical(show_bed_slope), ...
    'show_depth_offset', logical(show_depth_offset), ...
    'show_relief_amplitude', logical(show_relief_amplitude), ...
    'show_resolution', logical(show_resolution));
end

function state_map = create_default_bathymetry_dynamic_params(catalog_2d, catalog_3d, base_params)
state_map = struct();
catalog = [catalog_2d(:); catalog_3d(:)];
for idx = 1:numel(catalog)
    entry = catalog(idx);
    state_map.(entry.id) = create_default_bathymetry_state(entry, base_params);
end
end

function state = create_default_bathymetry_state(entry, base_params)
state = struct();
if isfield(entry, 'shared_flags') && isstruct(entry.shared_flags)
    flags = entry.shared_flags;
else
    flags = make_bathymetry_shared_flags(false, false, false, false);
end

defaults = struct();
if isfield(entry, 'shared_defaults') && isstruct(entry.shared_defaults)
    defaults = entry.shared_defaults;
end

if isfield(flags, 'show_bed_slope') && flags.show_bed_slope
    state.bed_slope = pick_struct_field(defaults, 'bed_slope', pick_struct_field(base_params, 'bathymetry_bed_slope', 0.03));
end
if isfield(flags, 'show_depth_offset') && flags.show_depth_offset
    state.depth_offset = pick_struct_field(defaults, 'depth_offset', pick_struct_field(base_params, 'bathymetry_depth_offset', 1000.0));
end
if isfield(flags, 'show_relief_amplitude') && flags.show_relief_amplitude
    state.relief_amplitude = pick_struct_field(defaults, 'relief_amplitude', pick_struct_field(base_params, 'bathymetry_relief_amplitude', 180.0));
end
if isfield(flags, 'show_resolution') && flags.show_resolution
    state.interpolation_resolution = round(pick_struct_field(defaults, 'interpolation_resolution', pick_struct_field(base_params, 'bathymetry_resolution', 96)));
end

if isfield(entry, 'dynamic_fields') && ~isempty(entry.dynamic_fields)
    for i = 1:numel(entry.dynamic_fields)
        field = entry.dynamic_fields(i);
        state.(field.id) = double(field.default);
    end
end
end

function value = pick_struct_field(source, field_name, fallback)
value = fallback;
if isstruct(source) && isfield(source, field_name)
    candidate = source.(field_name);
    if isnumeric(candidate)
        candidate = double(candidate);
    end
    if isscalar(candidate) && isfinite(candidate)
        value = candidate;
    end
end
end

function entry = make_simulation_scenario(name, description, overrides)
entry = struct( ...
    'scenario_name', char(string(name)), ...
    'description', char(string(description)), ...
    'overrides', overrides);
end

function preview_mode = resolve_ic_preview_mode(ic_type)
switch lower(char(string(ic_type)))
    case {'taylor_green', 'random_turbulence', 'no_initial_condition'}
        preview_mode = 'domain_field';
    otherwise
        preview_mode = 'localized_scalar';
end
end

function entries = create_default_where_entries(ic_type)
switch lower(char(string(ic_type)))
    case 'no_initial_condition'
        entries = [
            make_where_entry('\omega_0', 'initial vorticity field', '0 everywhere', ...
            'Starts the run from exact zero vorticity.', ...
            'Boundary forcing, diffusion, and advection generate the flow after launch.', 'shared')
            ];
    case 'stretched_gaussian'
        entries = [
            make_where_entry('a', 'x-stretch coefficient', '[0.1, 10]', ...
            'Controls anisotropic localization along x.', ...
            'Higher values sharpen the vortex core in x.', 'dynamic');
            make_where_entry('b', 'y-stretch coefficient', '[0.1, 10]', ...
            'Controls anisotropic localization along y.', ...
            'Higher values sharpen the vortex core in y.', 'dynamic');
            make_where_entry('x_0, y_0', 'center position', 'within domain bounds', ...
            'Shifts the vortex center.', ...
            'Moves the localized structure without changing its shape.', 'shared');
            make_where_entry('A', 'amplitude multiplier', '(0, 100]', ...
            'Rescales the peak vorticity.', ...
            'Larger values increase peak strength while preserving geometry.', 'shared')
            ];
    case 'vortex_blob_gaussian'
        entries = [
            make_where_entry('\Gamma', 'circulation', '[-100, 100]', ...
            'Sets the signed rotational strength.', ...
            'Positive/negative values flip vortex rotation.', 'dynamic');
            make_where_entry('R', 'core radius', '(0, 100]', ...
            'Sets Gaussian core size.', ...
            'Larger radius broadens the blob and lowers peak intensity.', 'dynamic');
            make_where_entry('x_0, y_0', 'center position', 'within domain bounds', ...
            'Translates the vortex blob.', ...
            'Moves the vortex without changing circulation.', 'shared')
            ];
    case 'vortex_pair'
        entries = [
            make_where_entry('\Gamma_1', 'primary circulation', '[-100, 100]', ...
            'Sets the first vortex strength.', ...
            'The partner vortex is configured as the opposing companion.', 'dynamic');
            make_where_entry('s', 'pair separation', '(0, 100]', ...
            'Controls center-to-center distance.', ...
            'Larger separation widens the dipole footprint.', 'dynamic');
            make_where_entry('R', 'core radius', '(0, 100]', ...
            'Sets the compactness of both vortices.', ...
            'Larger cores soften the pair interaction.', 'dynamic')
            ];
    case 'multi_vortex'
        entries = [
            make_where_entry('N', 'vortex count', '[1, 50]', ...
            'Sets how many localized vortices are generated.', ...
            'Counts above one activate arrangement logic.', 'shared');
            make_where_entry('pattern', 'arrangement token', '{single,circular,grid,random}', ...
            'Controls how centers are scattered.', ...
            'Determines the geometric footprint of the vortex pack.', 'shared');
            make_where_entry('\Gamma, R', 'per-vortex strength and radius', 'problem dependent', ...
            'Control circulation and compactness per generated vortex.', ...
            'These settings shape the local structure of each vortex.', 'dynamic')
            ];
    case 'lamb_oseen'
        entries = [
            make_where_entry('\Gamma', 'circulation', '[-100, 100]', ...
            'Controls total vortex strength.', ...
            'Larger magnitude increases rotational intensity.', 'dynamic');
            make_where_entry('t_0', 'virtual diffusion time', '(10^{-6}, 10^{6}]', ...
            'Broadens the Lamb-Oseen core.', ...
            'Higher values yield a smoother, more diffused vortex.', 'dynamic');
            make_where_entry('\nu', 'kinematic viscosity', '(10^{-10}, 10]', ...
            'Sets viscous spreading scale.', ...
            'Higher viscosity broadens and damps the core.', 'dynamic')
            ];
    case 'rankine'
        entries = [
            make_where_entry('\omega_0', 'core vorticity', '[-100, 100]', ...
            'Sets the constant plateau value inside the core.', ...
            'Higher magnitude increases rigid-body core rotation.', 'dynamic');
            make_where_entry('r_c', 'cutoff radius', '(0, 100]', ...
            'Sets the sharp core boundary.', ...
            'Larger radius expands the solid-body region.', 'dynamic')
            ];
    case 'lamb_dipole'
        entries = [
            make_where_entry('U', 'translation speed', '[-100, 100]', ...
            'Controls dipole propagation strength.', ...
            'Higher magnitude increases translational tendency.', 'dynamic');
            make_where_entry('a', 'dipole radius', '(0, 100]', ...
            'Sets the dipole footprint.', ...
            'Larger values widen the paired structure.', 'dynamic')
            ];
    case 'taylor_green'
        entries = [
            make_where_entry('m', 'domain mode count', '\{1,2,3,\ldots\}', ...
            'Sets the integer Taylor-Green mode count across both domain directions.', ...
            'Higher values create more periodic cells across the active domain.', 'dynamic');
            make_where_entry('G', 'velocity scale', '[-100, 100]', ...
            'Scales the divergence-free Taylor-Green velocity field.', ...
            'Larger magnitude increases the vorticity amplitude everywhere.', 'dynamic')
            ];
    case 'random_turbulence'
        entries = [
            make_where_entry('\alpha', 'spectrum exponent', '[0.1, 10]', ...
            'Controls high-wavenumber decay.', ...
            'Higher values suppress smaller turbulent structures.', 'dynamic');
            make_where_entry('E_0', 'energy level', '[10^{-8}, 10^{6}]', ...
            'Sets the overall turbulence energy scale.', ...
            'Higher values amplify the random field.', 'dynamic');
            make_where_entry('seed', 'random seed', '[0, 10^{9}]', ...
            'Fixes the realization of random phases.', ...
            'Changing the seed changes the field pattern reproducibly.', 'dynamic')
            ];
    case 'elliptical_vortex'
        entries = [
            make_where_entry('\omega_p', 'peak vorticity', '[-100, 100]', ...
            'Sets the vortex peak magnitude.', ...
            'Higher magnitude strengthens the elliptical core.', 'dynamic');
            make_where_entry('\sigma_x, \sigma_y', 'principal spreads', '(0, 100]', ...
            'Control ellipse width on each axis.', ...
            'Anisotropy changes elongation and compactness.', 'dynamic');
            make_where_entry('\theta', 'rotation angle', '[-2\pi, 2\pi]', ...
            'Rotates the ellipse.', ...
            'Changes the orientation of the elongated structure.', 'dynamic')
            ];
    otherwise
        entries = make_where_entry('IC', 'parameter guidance', 'problem dependent', ...
            'IC-specific parameter note.', 'See popup/detail editor for the active field semantics.', 'shared');
end
end

function entry = make_where_entry(symbol_tex, name, range_tex, effect_text, outcome_text, applies_to)
entry = struct( ...
    'symbol_tex', char(string(symbol_tex)), ...
    'name', char(string(name)), ...
    'range_tex', char(string(range_tex)), ...
    'effect_text', char(string(effect_text)), ...
    'outcome_text', char(string(outcome_text)), ...
    'applies_to', char(string(applies_to)));
end

function profiles = create_collector_machine_profiles()
profiles = struct( ...
    'laptop', struct( ...
        'aliases', {{'ASUS_ZENBOOK', 'ZENBOOK', 'LAPTOP', 'NOTEBOOK'}}, ...
        'panel_profile', 'laptop'), ...
    'desktop', struct( ...
        'aliases', {{'DESKTOP', 'MAIN_PC', 'MAIN_COMPUTER'}}, ...
        'panel_profile', 'desktop'));
end

function machine_profile = resolve_collector_machine_profile(machine_tag, profiles)
machine_profile = 'desktop';
machine_token = lower(strtrim(char(string(machine_tag))));
if isempty(machine_token)
    return;
end

profile_names = fieldnames(profiles);
for i = 1:numel(profile_names)
    profile_name = profile_names{i};
    aliases = profiles.(profile_name).aliases;
    alias_tokens = lower(string(aliases));
    if any(strcmp(machine_token, alias_tokens)) || contains(machine_token, lower(profile_name))
        machine_profile = profile_name;
        return;
    end
end

if contains(machine_token, 'zenbook') || contains(machine_token, 'laptop') || contains(machine_token, 'notebook')
    machine_profile = 'laptop';
end
end

function panel_profile = resolve_collector_panel_profile(machine_profile)
switch lower(strtrim(char(string(machine_profile))))
    case 'laptop'
        panel_profile = 'laptop';
    otherwise
        panel_profile = 'desktop';
end
end

function debug_ic_catalog(catalog, scenarios)
% Lightweight inspector for IC catalog and scenario structs.
% Call with `debug_ic_catalog(params.ic_ui_catalog, params.ic_scenario_catalog)`
%//TODO: This is a developer helper — wrap with a verbosity flag or remove before release.
if nargin < 1 || isempty(catalog)
    disp('debug_ic_catalog: catalog is empty or missing');
    return;
end
fprintf('debug_ic_catalog: %d catalog entries\n', numel(catalog));
for k = 1:numel(catalog)
    e = catalog(k);
    nfields = 0;
    try
        nfields = numel(e.dynamic_fields);
    catch
        nfields = -1;
    end
    fprintf('  %d: %s (%s) — dynamic_fields=%d\n', k, e.display_name, e.ic_type, nfields);
end
if nargin >= 2 && ~isempty(scenarios)
    fprintf('debug_ic_catalog: %d scenarios\n', numel(scenarios));
    for k = 1:numel(scenarios)
        s = scenarios(k);
        locked = double(s.lock_ic_type_dropdown);
        fprintf('  %d: %s -> forced=%s locked=%d\n', k, s.scenario_name, s.forced_ic_type, locked);
    end
end
end
