function s = Settings()
% Settings - Unified operational settings for run output and tooling.
%
% Canonical sections:
%   output_root
%   reporting.*
%   media.*
%   sustainability.*
%
% Compatibility aliases are preserved for existing scripts.

    % ---------------------------------------------------------------------
    % Output root
    % ---------------------------------------------------------------------
    s.output_root = 'Results';

    % ---------------------------------------------------------------------
    % Persistence toggles
    % ---------------------------------------------------------------------
    s.save_figures = true;
    s.save_data = true;
    s.save_json = false;
    s.append_to_master = true;

    % ---------------------------------------------------------------------
    % Monitoring and UI
    % ---------------------------------------------------------------------
    s.monitor_enabled = true;
    s.sample_interval = 0.5;
    s.monitor_theme = 'dark';
    s.terminal_capture = true;
    s.log_level = 'INFO';       % DEBUG | INFO | WARN | ERROR
    s.resource_allocation = struct( ...
        'cpu_target_pct', 80, ...
        'memory_target_pct', 70, ...
        'gpu_target_pct', 80, ...
        'monitor_hz', 2, ...
        'progress_hz', 6, ...
        'pool_workers', 1, ...
        'resource_strategy', 'mode_adaptive', ...
        'gpu_policy', 'auto', ...
        'planner_use_host_profiles', true, ...
        'interactive_pool_workers_max', 2, ...
        'throughput_pool_workers_min', 2, ...
        'interactive_thread_headroom_pct', 75, ...
        'gpu_min_workload_cells_steps', 0, ...
        'gpu_memory_guard_pct', 80, ...
        'pool_workers_max_override', 0, ...
        'pool_workers_requested', 1, ...
        'pool_workers_effective', 1, ...
        'thread_cap', 1, ...
        'gpu_enabled_effective', false, ...
        'host_profile_id', 'none', ...
        'planner_notes', {{'defaults_loaded'}});

    % ---------------------------------------------------------------------
    % Figure formatting
    % ---------------------------------------------------------------------
    s.figure_format = 'fig';    % fig is the user-facing artifact format
    s.figure_dpi = 600;
    s.figure_save_png = false;
    s.figure_save_pdf = false;
    s.figure_save_fig = true;

    % ---------------------------------------------------------------------
    % Reporting policy
    % ---------------------------------------------------------------------
    s.reporting = struct();
    s.reporting.enabled = true;
    s.reporting.engine = 'quarto';   % quarto with internal fallback
    s.reporting.template = 'default';
    s.reporting.formats = {'html', 'pdf'};
    s.reporting.max_rows = 500;
    s.reporting.max_figures = 24;

    % Compatibility alias used across current code.
    s.save_reports = s.reporting.enabled;

    % ---------------------------------------------------------------------
    % Media/animation policy
    % ---------------------------------------------------------------------
    s.media = struct();
    s.media.enabled = true;
    s.media.format = 'mp4+gif';
    s.media.formats = {'mp4', 'gif'};
    s.media.codec = 'MPEG-4';
    s.media.fps = 30;
    s.media.duration_s = 10;
    s.media.frame_count = 300;
    s.media.gif_min_frame_count = 100;
    s.media.quality = 90;
    s.media.dpi = 600;
    s.media.preset = 'double_column_report';
    s.media.width_in = 7.16;
    s.media.height_in = 5.37;
    s.media.resolution_px = [4296, 3222];

    % Compatibility aliases used by existing scripts.
    s.animation_enabled = s.media.enabled;
    s.tile_snapshot_count = 9;             % For 3x3 tiled summary plots
    s.animation_frame_rate = s.media.fps;  % Frames per second
    s.animation_frame_count = s.media.frame_count;
    s.animation_format = s.media.format;
    s.animation_export_format = s.media.format;
    s.animation_export_formats = s.media.formats;
    s.animation_gif_min_frames = s.media.gif_min_frame_count;
    s.animation_quality = s.media.quality;
    s.animation_codec = s.media.codec;
    s.animation_fps = s.animation_frame_rate;
    s.animation_duration_s = s.media.duration_s;
    s.animation_export_dpi = s.media.dpi;
    s.animation_export_preset = s.media.preset;
    s.animation_export_width_in = s.media.width_in;
    s.animation_export_height_in = s.media.height_in;
    s.animation_export_resolution_px = s.media.resolution_px;

    % ---------------------------------------------------------------------
    % Sustainability policy (always-on ledger, optional enrichers)
    % ---------------------------------------------------------------------
    s.sustainability = struct();
    s.sustainability.enabled = true;
    s.sustainability.sample_interval = s.sample_interval;
    s.sustainability.machine_id = 'auto';      % auto uses hostname/computername
    s.sustainability.machine_label = '';       % optional display label
    s.sustainability.environmental_model = struct( ...
        'electricity_scope', 'consumed_location_based', ...
        'grid_carbon_intensity_kgco2e_per_kwh', 0.19553, ...
        'grid_carbon_intensity_gco2e_per_kwh', 195.53, ...
        'factor_year', 2025, ...
        'factor_region', 'UK', ...
        'factor_source_tag', 'uk_gov_2025_consumed_2023data', ...
        'factor_source_url', 'https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2025', ...
        'line_losses_included', true, ...
        'allow_component_power_sum_fallback', true, ...
        'detect_apu_power_duplication', true);
    s.sustainability.external_collectors = struct( ...
        'hwinfo', false, ...
        'icue', false);
    s.sustainability.collector_paths = struct( ...
        'hwinfo', '', ...
        'icue', '');
    s.sustainability.collector_runtime = struct( ...
        'session_output_dir', '', ...
        'session_csv_path', '', ...
        'collector_launch_root_dir', '', ...
        'collector_launch_csv_file', 'launch_telemetry.csv', ...
        'hwinfo_shared_memory_blob_path', '', ...
        'hwinfo_control_mode', 'pro_cli_csv', ...
        'hwinfo_pro_cli_enabled', true, ...
        'hwinfo_pro_log_write_direct', true, ...
        'hwinfo_pro_poll_rate_ms', 1000, ...
        'hwinfo_pro_launch_timeout_s', 20, ...
        'hwinfo_pro_csv_timeout_s', 45, ...
        'hwinfo_pro_force_stop_fallback', true, ...
        'hwinfo_pro_csv_path', '', ...
        'hwinfo_transport_mode', 'auto', ...
        'hwinfo_csv_target_dir', '', ...
        'hwinfo_csv_target_path', '', ...
        'hwinfo_csv_dir', '', ...
        'hwinfo_csv_path', '', ...
        'icue_csv_dir', '', ...
        'icue_csv_path', '', ...
        'icue_user_props_path', '', ...
        'icue_config_path', '', ...
        'icue_devices_path', '');

    % ---------------------------------------------------------------------
    % Validation/normalization guards
    % ---------------------------------------------------------------------
    if s.tile_snapshot_count < 1
        s.tile_snapshot_count = 9;
    end
    if s.animation_frame_rate <= 0
        s.animation_frame_rate = 30;
    end
    if s.animation_frame_count < 2
        s.animation_frame_count = 300;
    end
end
